import { type Chapter, chapterSchema } from "@/lib/schema";

// Les 1: het Griekse alfabet.
// Deel A (nl->el): Nederlandse naam (+ transliteratie) -> Griekse kleine letter (meerkeuze).
// Deel B (el->nl): Griekse kleine letter -> Latijnse transliteratie / naam (typen).
// Deel C (nl->el): Nederlandse naam HOOFDLETTER -> Griekse hoofdletter (meerkeuze).
// Antwoorden accepteren zowel de letter-naam als de transliteratie,
// zodat "alpha is a" én "β -> b" allebei geoefend worden.

const rawChapter = {
	id: "greek-alfabet",
	title: "Ελληνικά – Het alfabet: leer de Griekse letters",
	description:
		"Leer alle 24 Griekse letters: van naam naar kleine letter (α), van kleine letter naar Latijnse letter (β → b) en de hoofdletters (Β). Tip: gebruik de Griekse balk om letters in te voegen.",
	language: "greek",
	exercises: [
		// Deel A: naam -> kleine letter (meerkeuze)
		{
			id: "alpha-a1",
			type: "vocab",
			prompt: "alpha (= a, kleine letter)",
			answer: "α",
			direction: "nl->el",
			hint: "Hoofdletter: Α • klinkt als a",
			options: ["α", "ε", "ο", "σ"],
		},
		{
			id: "alpha-a2",
			type: "vocab",
			prompt: "bèta (= b, kleine letter)",
			answer: "β",
			direction: "nl->el",
			hint: "Hoofdletter: Β • klinkt als b",
			options: ["β", "θ", "φ", "ψ"],
		},
		{
			id: "alpha-a3",
			type: "vocab",
			prompt: "gamma (= g, kleine letter)",
			answer: "γ",
			direction: "nl->el",
			hint: "Hoofdletter: Γ • klinkt als g",
			options: ["γ", "λ", "χ", "π"],
		},
		{
			id: "alpha-a4",
			type: "vocab",
			prompt: "delta (= d, kleine letter)",
			answer: "δ",
			direction: "nl->el",
			hint: "Hoofdletter: Δ • klinkt als d",
			options: ["δ", "θ", "λ", "α"],
		},
		{
			id: "alpha-a5",
			type: "vocab",
			prompt: "epsilon (= korte e, kleine letter)",
			answer: "ε",
			direction: "nl->el",
			hint: "Hoofdletter: Ε • klinkt als e in 'bed'",
			options: ["ε", "σ", "ο", "α"],
		},
		{
			id: "alpha-a6",
			type: "vocab",
			prompt: "zèta (= z, kleine letter)",
			answer: "ζ",
			direction: "nl->el",
			hint: "Hoofdletter: Ζ • klinkt als z",
			options: ["ζ", "ξ", "σ", "ε"],
		},
		{
			id: "alpha-a7",
			type: "vocab",
			prompt: "èta (= lange e, kleine letter)",
			answer: "η",
			direction: "nl->el",
			hint: "Hoofdletter: Η • klinkt als i (lange e)",
			options: ["η", "ι", "υ", "μ"],
		},
		{
			id: "alpha-a8",
			type: "vocab",
			prompt: "thèta (= th, kleine letter)",
			answer: "θ",
			direction: "nl->el",
			hint: "Hoofdletter: Θ • klinkt als th in 'think'",
			options: ["θ", "β", "φ", "ο"],
		},
		{
			id: "alpha-a9",
			type: "vocab",
			prompt: "iota (= i, kleine letter)",
			answer: "ι",
			direction: "nl->el",
			hint: "Hoofdletter: Ι • klinkt als i",
			options: ["ι", "η", "υ", "τ"],
		},
		{
			id: "alpha-a10",
			type: "vocab",
			prompt: "kappa (= k, kleine letter)",
			answer: "κ",
			direction: "nl->el",
			hint: "Hoofdletter: Κ • klinkt als k",
			options: ["κ", "χ", "λ", "ν"],
		},
		{
			id: "alpha-a11",
			type: "vocab",
			prompt: "lambda (= l, kleine letter)",
			answer: "λ",
			direction: "nl->el",
			hint: "Hoofdletter: Λ • klinkt als l",
			options: ["λ", "γ", "χ", "δ"],
		},
		{
			id: "alpha-a12",
			type: "vocab",
			prompt: "mu (= m, kleine letter)",
			answer: "μ",
			direction: "nl->el",
			hint: "Hoofdletter: Μ • klinkt als m",
			options: ["μ", "η", "ν", "ω"],
		},
		{
			id: "alpha-a13",
			type: "vocab",
			prompt: "nu (= n, kleine letter)",
			answer: "ν",
			direction: "nl->el",
			hint: "Hoofdletter: Ν • klinkt als n (let op: lijkt op v)",
			options: ["ν", "υ", "μ", "ι"],
		},
		{
			id: "alpha-a14",
			type: "vocab",
			prompt: "xi (= x, kleine letter)",
			answer: "ξ",
			direction: "nl->el",
			hint: "Hoofdletter: Ξ • klinkt als x",
			options: ["ξ", "ζ", "χ", "ψ"],
		},
		{
			id: "alpha-a15",
			type: "vocab",
			prompt: "omikron (= korte o, kleine letter)",
			answer: "ο",
			direction: "nl->el",
			hint: "Hoofdletter: Ο • klinkt als o in 'pot'",
			options: ["ο", "σ", "α", "θ"],
		},
		{
			id: "alpha-a16",
			type: "vocab",
			prompt: "pi (= p, kleine letter)",
			answer: "π",
			direction: "nl->el",
			hint: "Hoofdletter: Π • klinkt als p",
			options: ["π", "γ", "τ", "η"],
		},
		{
			id: "alpha-a17",
			type: "vocab",
			prompt: "rho (= r, kleine letter)",
			answer: "ρ",
			direction: "nl->el",
			hint: "Hoofdletter: Ρ • klinkt als r (let op: lijkt op p)",
			options: ["ρ", "φ", "β", "π"],
		},
		{
			id: "alpha-a18",
			type: "vocab",
			prompt: "sigma (= s, kleine letter, midden in een woord)",
			answer: "σ",
			direction: "nl->el",
			hint: "Hoofdletter: Σ • aan het eind van een woord schrijf je ς",
			options: ["σ", "ε", "ο", "ς"],
		},
		{
			id: "alpha-a19",
			type: "vocab",
			prompt: "tau (= t, kleine letter)",
			answer: "τ",
			direction: "nl->el",
			hint: "Hoofdletter: Τ • klinkt als t",
			options: ["τ", "π", "ι", "γ"],
		},
		{
			id: "alpha-a20",
			type: "vocab",
			prompt: "upsilon (= u/y, kleine letter)",
			answer: "υ",
			direction: "nl->el",
			hint: "Hoofdletter: Υ • klinkt als i",
			options: ["υ", "ν", "ι", "η"],
		},
		{
			id: "alpha-a21",
			type: "vocab",
			prompt: "phi (= ph/f, kleine letter)",
			answer: "φ",
			direction: "nl->el",
			hint: "Hoofdletter: Φ • klinkt als f",
			options: ["φ", "β", "θ", "ψ"],
		},
		{
			id: "alpha-a22",
			type: "vocab",
			prompt: "chi (= ch, kleine letter)",
			answer: "χ",
			direction: "nl->el",
			hint: "Hoofdletter: Χ • klinkt als ch in 'lach'",
			options: ["χ", "γ", "λ", "κ"],
		},
		{
			id: "alpha-a23",
			type: "vocab",
			prompt: "psi (= ps, kleine letter)",
			answer: "ψ",
			direction: "nl->el",
			hint: "Hoofdletter: Ψ • klinkt als ps",
			options: ["ψ", "φ", "ξ", "β"],
		},
		{
			id: "alpha-a24",
			type: "vocab",
			prompt: "omega (= lange o, kleine letter)",
			answer: "ω",
			direction: "nl->el",
			hint: "Hoofdletter: Ω • klinkt als o (lange o)",
			options: ["ω", "ο", "μ", "σ"],
		},
		// Deel B: kleine letter -> Latijnse letter / naam (typen)
		{
			id: "alpha-b1",
			type: "vocab",
			prompt: "α",
			answer: "a",
			alternatives: ["alpha"],
			direction: "el->nl",
			hint: "kleine letter • naam: alpha • klinkt als a",
		},
		{
			id: "alpha-b2",
			type: "vocab",
			prompt: "β",
			answer: "b",
			alternatives: ["beta", "bèta"],
			direction: "el->nl",
			hint: "kleine letter • naam: bèta • klinkt als b",
		},
		{
			id: "alpha-b3",
			type: "vocab",
			prompt: "γ",
			answer: "g",
			alternatives: ["gamma"],
			direction: "el->nl",
			hint: "kleine letter • naam: gamma • klinkt als g",
		},
		{
			id: "alpha-b4",
			type: "vocab",
			prompt: "δ",
			answer: "d",
			alternatives: ["delta"],
			direction: "el->nl",
			hint: "kleine letter • naam: delta • klinkt als d",
		},
		{
			id: "alpha-b5",
			type: "vocab",
			prompt: "ε",
			answer: "epsilon",
			alternatives: ["e"],
			direction: "el->nl",
			hint: "kleine letter • korte e, als in 'bed'",
			options: ["epsilon", "eta", "sigma", "alpha"],
		},
		{
			id: "alpha-b6",
			type: "vocab",
			prompt: "ζ",
			answer: "z",
			alternatives: ["zeta", "zèta"],
			direction: "el->nl",
			hint: "kleine letter • naam: zèta • klinkt als z",
		},
		{
			id: "alpha-b7",
			type: "vocab",
			prompt: "η",
			answer: "eta",
			alternatives: ["e", "èta"],
			direction: "el->nl",
			hint: "kleine letter • lange e, klinkt als i",
			options: ["eta", "epsilon", "iota", "mu"],
		},
		{
			id: "alpha-b8",
			type: "vocab",
			prompt: "θ",
			answer: "th",
			alternatives: ["theta", "thèta"],
			direction: "el->nl",
			hint: "kleine letter • naam: thèta • als th in 'think'",
		},
		{
			id: "alpha-b9",
			type: "vocab",
			prompt: "ι",
			answer: "i",
			alternatives: ["iota"],
			direction: "el->nl",
			hint: "kleine letter • naam: iota • klinkt als i",
		},
		{
			id: "alpha-b10",
			type: "vocab",
			prompt: "κ",
			answer: "k",
			alternatives: ["kappa"],
			direction: "el->nl",
			hint: "kleine letter • naam: kappa • klinkt als k",
		},
		{
			id: "alpha-b11",
			type: "vocab",
			prompt: "λ",
			answer: "l",
			alternatives: ["lambda"],
			direction: "el->nl",
			hint: "kleine letter • naam: lambda • klinkt als l",
		},
		{
			id: "alpha-b12",
			type: "vocab",
			prompt: "μ",
			answer: "m",
			alternatives: ["mu"],
			direction: "el->nl",
			hint: "kleine letter • naam: mu • klinkt als m",
		},
		{
			id: "alpha-b13",
			type: "vocab",
			prompt: "ν",
			answer: "n",
			alternatives: ["nu"],
			direction: "el->nl",
			hint: "kleine letter • naam: nu • klinkt als n (lijkt op v, maar is geen v!)",
			options: ["n", "v", "m", "u"],
		},
		{
			id: "alpha-b14",
			type: "vocab",
			prompt: "ξ",
			answer: "x",
			alternatives: ["xi"],
			direction: "el->nl",
			hint: "kleine letter • naam: xi • klinkt als x",
		},
		{
			id: "alpha-b15",
			type: "vocab",
			prompt: "ο",
			answer: "omikron",
			alternatives: ["o", "omicron"],
			direction: "el->nl",
			hint: "kleine letter • korte o, als in 'pot'",
			options: ["omikron", "omega", "sigma", "alpha"],
		},
		{
			id: "alpha-b16",
			type: "vocab",
			prompt: "π",
			answer: "p",
			alternatives: ["pi"],
			direction: "el->nl",
			hint: "kleine letter • naam: pi • klinkt als p",
		},
		{
			id: "alpha-b17",
			type: "vocab",
			prompt: "ρ",
			answer: "r",
			alternatives: ["rho"],
			direction: "el->nl",
			hint: "kleine letter • naam: rho • klinkt als r (lijkt op p, maar is geen p!)",
			options: ["r", "p", "b", "f"],
		},
		{
			id: "alpha-b18",
			type: "vocab",
			prompt: "σ",
			answer: "s",
			alternatives: ["sigma"],
			direction: "el->nl",
			hint: "kleine letter • sigma midden in een woord (eindvorm: ς)",
		},
		{
			id: "alpha-b19",
			type: "vocab",
			prompt: "τ",
			answer: "t",
			alternatives: ["tau"],
			direction: "el->nl",
			hint: "kleine letter • naam: tau • klinkt als t",
		},
		{
			id: "alpha-b20",
			type: "vocab",
			prompt: "υ",
			answer: "u",
			alternatives: ["upsilon", "y"],
			direction: "el->nl",
			hint: "kleine letter • naam: upsilon • klinkt als i",
		},
		{
			id: "alpha-b21",
			type: "vocab",
			prompt: "φ",
			answer: "f",
			alternatives: ["phi", "ph"],
			direction: "el->nl",
			hint: "kleine letter • naam: phi • klinkt als f",
		},
		{
			id: "alpha-b22",
			type: "vocab",
			prompt: "χ",
			answer: "ch",
			alternatives: ["chi"],
			direction: "el->nl",
			hint: "kleine letter • naam: chi • als ch in 'lach'",
		},
		{
			id: "alpha-b23",
			type: "vocab",
			prompt: "ψ",
			answer: "ps",
			alternatives: ["psi"],
			direction: "el->nl",
			hint: "kleine letter • naam: psi • klinkt als ps",
		},
		{
			id: "alpha-b24",
			type: "vocab",
			prompt: "ω",
			answer: "omega",
			alternatives: ["o"],
			direction: "el->nl",
			hint: "kleine letter • lange o",
			options: ["omega", "omikron", "mu", "sigma"],
		},
		{
			id: "alpha-b25",
			type: "vocab",
			prompt: "ς (aan het eind van een woord)",
			answer: "s",
			alternatives: ["sigma", "eindsigma"],
			direction: "el->nl",
			hint: "Dit is de eindvorm van sigma (σ): alleen aan het woordeinde, klinkt als s",
			options: ["s", "e", "o", "c"],
		},
		// Deel C: naam HOOFDLETTER -> hoofdletter (meerkeuze)
		{
			id: "alpha-c1",
			type: "vocab",
			prompt: "ALPHA (= A, HOOFDLETTER)",
			answer: "Α",
			direction: "nl->el",
			hint: "Kleine letter: α",
			options: ["Α", "Δ", "Λ", "Ε"],
		},
		{
			id: "alpha-c2",
			type: "vocab",
			prompt: "BÈTA (= B, HOOFDLETTER)",
			answer: "Β",
			direction: "nl->el",
			hint: "Kleine letter: β",
			options: ["Β", "Ρ", "Ε", "Η"],
		},
		{
			id: "alpha-c3",
			type: "vocab",
			prompt: "GAMMA (= G, HOOFDLETTER)",
			answer: "Γ",
			direction: "nl->el",
			hint: "Kleine letter: γ",
			options: ["Γ", "Π", "Τ", "Λ"],
		},
		{
			id: "alpha-c4",
			type: "vocab",
			prompt: "DELTA (= D, HOOFDLETTER)",
			answer: "Δ",
			direction: "nl->el",
			hint: "Kleine letter: δ",
			options: ["Δ", "Α", "Λ", "Θ"],
		},
		{
			id: "alpha-c5",
			type: "vocab",
			prompt: "EPSILON (= E, HOOFDLETTER)",
			answer: "Ε",
			direction: "nl->el",
			hint: "Kleine letter: ε",
			options: ["Ε", "Β", "Η", "Ξ"],
		},
		{
			id: "alpha-c6",
			type: "vocab",
			prompt: "ZÈTA (= Z, HOOFDLETTER)",
			answer: "Ζ",
			direction: "nl->el",
			hint: "Kleine letter: ζ",
			options: ["Ζ", "Ξ", "Η", "Ε"],
		},
		{
			id: "alpha-c7",
			type: "vocab",
			prompt: "ÈTA (= lange E, HOOFDLETTER)",
			answer: "Η",
			direction: "nl->el",
			hint: "Kleine letter: η (lijkt op H!)",
			options: ["Η", "Ε", "Β", "Ν"],
		},
		{
			id: "alpha-c8",
			type: "vocab",
			prompt: "THÈTA (= TH, HOOFDLETTER)",
			answer: "Θ",
			direction: "nl->el",
			hint: "Kleine letter: θ",
			options: ["Θ", "Ο", "Φ", "Β"],
		},
		{
			id: "alpha-c9",
			type: "vocab",
			prompt: "IOTA (= I, HOOFDLETTER)",
			answer: "Ι",
			direction: "nl->el",
			hint: "Kleine letter: ι",
			options: ["Ι", "Η", "Τ", "Γ"],
		},
		{
			id: "alpha-c10",
			type: "vocab",
			prompt: "KAPPA (= K, HOOFDLETTER)",
			answer: "Κ",
			direction: "nl->el",
			hint: "Kleine letter: κ",
			options: ["Κ", "Χ", "Ν", "Η"],
		},
		{
			id: "alpha-c11",
			type: "vocab",
			prompt: "LAMBDA (= L, HOOFDLETTER)",
			answer: "Λ",
			direction: "nl->el",
			hint: "Kleine letter: λ",
			options: ["Λ", "Α", "Δ", "Γ"],
		},
		{
			id: "alpha-c12",
			type: "vocab",
			prompt: "MU (= M, HOOFDLETTER)",
			answer: "Μ",
			direction: "nl->el",
			hint: "Kleine letter: μ",
			options: ["Μ", "Ν", "Η", "Ξ"],
		},
		{
			id: "alpha-c13",
			type: "vocab",
			prompt: "NU (= N, HOOFDLETTER)",
			answer: "Ν",
			direction: "nl->el",
			hint: "Kleine letter: ν",
			options: ["Ν", "Μ", "Η", "Ζ"],
		},
		{
			id: "alpha-c14",
			type: "vocab",
			prompt: "XI (= X, HOOFDLETTER)",
			answer: "Ξ",
			direction: "nl->el",
			hint: "Kleine letter: ξ",
			options: ["Ξ", "Ζ", "Ε", "Η"],
		},
		{
			id: "alpha-c15",
			type: "vocab",
			prompt: "OMIKRON (= O, HOOFDLETTER)",
			answer: "Ο",
			direction: "nl->el",
			hint: "Kleine letter: ο",
			options: ["Ο", "Θ", "Ε", "Ω"],
		},
		{
			id: "alpha-c16",
			type: "vocab",
			prompt: "PI (= P, HOOFDLETTER)",
			answer: "Π",
			direction: "nl->el",
			hint: "Kleine letter: π",
			options: ["Π", "Γ", "Τ", "Η"],
		},
		{
			id: "alpha-c17",
			type: "vocab",
			prompt: "RHO (= R, HOOFDLETTER)",
			answer: "Ρ",
			direction: "nl->el",
			hint: "Kleine letter: ρ (lijkt op P!)",
			options: ["Ρ", "Β", "Π", "Γ"],
		},
		{
			id: "alpha-c18",
			type: "vocab",
			prompt: "SIGMA (= S, HOOFDLETTER)",
			answer: "Σ",
			direction: "nl->el",
			hint: "Kleine letters: σ (midden) en ς (einde)",
			options: ["Σ", "Ε", "Ζ", "Ξ"],
		},
		{
			id: "alpha-c19",
			type: "vocab",
			prompt: "TAU (= T, HOOFDLETTER)",
			answer: "Τ",
			direction: "nl->el",
			hint: "Kleine letter: τ",
			options: ["Τ", "Π", "Γ", "Ι"],
		},
		{
			id: "alpha-c20",
			type: "vocab",
			prompt: "UPSILON (= U, HOOFDLETTER)",
			answer: "Υ",
			direction: "nl->el",
			hint: "Kleine letter: υ (lijkt op Y!)",
			options: ["Υ", "Τ", "Η", "Χ"],
		},
		{
			id: "alpha-c21",
			type: "vocab",
			prompt: "PHI (= PH, HOOFDLETTER)",
			answer: "Φ",
			direction: "nl->el",
			hint: "Kleine letter: φ",
			options: ["Φ", "Θ", "Ψ", "Ρ"],
		},
		{
			id: "alpha-c22",
			type: "vocab",
			prompt: "CHI (= CH, HOOFDLETTER)",
			answer: "Χ",
			direction: "nl->el",
			hint: "Kleine letter: χ (lijkt op X!)",
			options: ["Χ", "Κ", "Υ", "Λ"],
		},
		{
			id: "alpha-c23",
			type: "vocab",
			prompt: "PSI (= PS, HOOFDLETTER)",
			answer: "Ψ",
			direction: "nl->el",
			hint: "Kleine letter: ψ",
			options: ["Ψ", "Φ", "Ξ", "Ζ"],
		},
		{
			id: "alpha-c24",
			type: "vocab",
			prompt: "OMEGA (= lange O, HOOFDLETTER)",
			answer: "Ω",
			direction: "nl->el",
			hint: "Kleine letter: ω",
			options: ["Ω", "Ο", "Μ", "Θ"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
