import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "greek-1",
	title: "Ελληνικά – Beginner 1 : Γειά σου!",
	description:
		"Basilat begroetingen, alledaagse woorden en het alfabet. Tip: gebruik de Griekse balk om letters in te voegen.",
	language: "greek",
	exercises: [
		{
			id: "el1-1",
			type: "vocab",
			prompt: "hallo (informeel, tegen één persoon)",
			answer: "γεια σου",
			direction: "nl->el",
			hint: "γεια σου – uitspraak: ya sou",
		},
		{
			id: "el1-2",
			type: "vocab",
			prompt: "γεια σου",
			answer: "hallo",
			direction: "el->nl",
			options: ["hallo", "tot ziens", "dank je", "ja"],
		},
		{
			id: "el1-3",
			type: "vocab",
			prompt: "dank je",
			answer: "ευχαριστώ",
			direction: "nl->el",
			hint: "ευχαριστώ – efcharistó",
		},
		{
			id: "el1-4",
			type: "vocab",
			prompt: "ευχαριστώ",
			answer: "dank je, bedankt",
			alternatives: ["dank je", "bedankt"],
			direction: "el->nl",
			options: ["dank je, bedankt", "alstublieft", "hallo", "nee"],
		},
		{
			id: "el1-5",
			type: "vocab",
			prompt: "ja",
			answer: "ναι",
			direction: "nl->el",
			options: ["ναι", "όχι", "παρακαλώ", "γεια"],
		},
		{
			id: "el1-6",
			type: "vocab",
			prompt: "nee",
			answer: "όχι",
			direction: "nl->el",
			hint: "Let op accent: ό",
		},
		{
			id: "el1-7",
			type: "vocab",
			prompt: "water",
			answer: "νερό",
			direction: "nl->el",
			hint: "νερό (onzijdig) – uitspraak: neró",
		},
		{
			id: "el1-8",
			type: "vocab",
			prompt: "νερό",
			answer: "water",
			direction: "el->nl",
			options: ["water", "brood", "huis", "wijn"],
		},
		{
			id: "el1-9",
			type: "vocab",
			prompt: "het huis",
			answer: "το σπίτι",
			direction: "nl->el",
			hint: "το σπίτι (onzijdig)",
		},
		{
			id: "el1-10",
			type: "vocab",
			prompt: "brood",
			answer: "ψωμί",
			direction: "nl->el",
			hint: "ψωμί – psomí",
		},
		{
			id: "el1-11",
			type: "declension",
			prompt: "είμαι – ik ben (1e persoon enkelvoud)",
			lemma: "είμαι – zijn",
			form: "εγώ ...",
			answer: "είμαι",
			hint: "εγώ είμαι, εσύ είσαι, αυτός είναι",
			options: ["είμαι", "είσαι", "είναι", "έχω"],
		},
		{
			id: "el1-12",
			type: "declension",
			prompt: "έχω – wij hebben (1e persoon meervoud)",
			lemma: "έχω – hebben",
			form: "εμείς ...",
			answer: "έχουμε",
			hint: "έχω, έχεις, έχει, έχουμε, έχετε, έχουν",
		},
		{
			id: "el1-13",
			type: "vocab",
			prompt: "alstublieft",
			answer: "παρακαλώ",
			direction: "nl->el",
		},
		{
			id: "el1-14",
			type: "vocab",
			prompt: "καλημέρα",
			answer: "goedemorgen",
			direction: "el->nl",
			options: ["goedemorgen", "goedenavond", "tot ziens", "welterusten"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
