import { type Chapter, chapterSchema } from "@/lib/schema";

// Les 3: klassiek Grieks (Herodotus-vormen: θάλαττα, εἰσί).
// Grieks -> Nederlands als type-oefening (je typt alleen Nederlands).
// Nederlands -> Grieks als meerkeuze: zo hoef je geen ademtekens
// (ἐ, ὁ, ῆ) te typen, die staan niet op de Griekse invoerbalk.
// De hint geeft telkens de uitspraak (transliteratie).

const rawChapter = {
	id: "greek-klassiek-1",
	title: "Ἑλληνικά – Klassiek 1: ἐν ἀρχῇ (in het begin)",
	description:
		"Klassieke woorden bij Herodotus: lidwoorden, ‘zijn’, natuur, mens, oorlog en vrede. Grieks → Nederlands typen, Nederlands → Grieks meerkeuze. Uitspraak staat in de hints.",
	language: "greek",
	exercises: [
		{
			id: "cl1-01",
			type: "vocab",
			prompt: "ἐν ἀρχῇ",
			answer: "in het begin",
			direction: "el->nl",
			hint: "uitspraak: en archè",
		},
		{
			id: "cl1-02",
			type: "vocab",
			prompt: "in het begin",
			answer: "ἐν ἀρχῇ",
			direction: "nl->el",
			options: ["ἐν ἀρχῇ", "πρῶτον", "ἐστί(ν)", "ἡ εἰρήνη"],
		},
		{
			id: "cl1-03",
			type: "vocab",
			prompt: "ἐστί(ν)",
			answer: "is, bestaat",
			alternatives: ["is", "bestaat"],
			direction: "el->nl",
			hint: "uitspraak: esti(n) • (hij/zij/het/er) …",
		},
		{
			id: "cl1-04",
			type: "vocab",
			prompt: "(hij/zij/het/er) is, bestaat",
			answer: "ἐστί(ν)",
			direction: "nl->el",
			options: ["ἐστί(ν)", "εἰσί(ν)", "ἐν ἀρχῇ", "ὁ θεός"],
		},
		{
			id: "cl1-05",
			type: "vocab",
			prompt: "ὁ, ἡ, τό",
			answer: "de, het",
			alternatives: ["de", "het"],
			direction: "el->nl",
			hint: "uitspraak: ho, hè, to • lidwoord: mannelijk, vrouwelijk, onzijdig",
		},
		{
			id: "cl1-06",
			type: "vocab",
			prompt: "de, het (lidwoord)",
			answer: "ὁ, ἡ, τό",
			direction: "nl->el",
			options: ["ὁ, ἡ, τό", "ὁ θεός", "τὸ Χάος", "ἡ γῆ"],
		},
		{
			id: "cl1-07",
			type: "vocab",
			prompt: "τὸ Χάος",
			answer: "Chaos",
			direction: "el->nl",
			hint: "uitspraak: to Chaos",
		},
		{
			id: "cl1-08",
			type: "vocab",
			prompt: "Chaos",
			answer: "τὸ Χάος",
			direction: "nl->el",
			options: ["τὸ Χάος", "ὁ πόλεμος", "τὸ ἔργον", "ὁ θεός"],
		},
		{
			id: "cl1-09",
			type: "vocab",
			prompt: "οὐ (voor medeklinker)",
			answer: "niet",
			direction: "el->nl",
			hint: "uitspraak: ou • voor klinker: οὐκ, voor klinker met ruwe geest: οὐχ",
		},
		{
			id: "cl1-10",
			type: "vocab",
			prompt: "niet",
			answer: "οὐ",
			direction: "nl->el",
			options: ["οὐ", "οὐδέ", "δέ", "ἐστί(ν)"],
		},
		{
			id: "cl1-11",
			type: "vocab",
			prompt: "ἡ γῆ",
			answer: "land, aarde",
			alternatives: ["land", "aarde"],
			direction: "el->nl",
			hint: "uitspraak: hè gè",
		},
		{
			id: "cl1-12",
			type: "vocab",
			prompt: "land, aarde",
			answer: "ἡ γῆ",
			direction: "nl->el",
			options: ["ἡ γῆ", "ἡ θάλαττα", "ἡ πέτρα", "ἡ μάχη"],
		},
		{
			id: "cl1-13",
			type: "vocab",
			prompt: "ἡ θάλαττα",
			answer: "zee",
			direction: "el->nl",
			hint: "uitspraak: hè thalatta (Attisch: θάλασσα)",
		},
		{
			id: "cl1-14",
			type: "vocab",
			prompt: "zee",
			answer: "ἡ θάλαττα",
			direction: "nl->el",
			options: ["ἡ θάλαττα", "ὁ ποταμός", "ἡ γῆ", "τὸ ζῷον"],
		},
		{
			id: "cl1-15",
			type: "vocab",
			prompt: "εἰσί(ν)",
			answer: "zijn, bestaan",
			alternatives: ["zijn", "bestaan"],
			direction: "el->nl",
			hint: "uitspraak: eisi(n) • (zij/er) … (meervoud van ἐστί)",
		},
		{
			id: "cl1-16",
			type: "vocab",
			prompt: "(zij/er) zijn, bestaan",
			answer: "εἰσί(ν)",
			direction: "nl->el",
			options: ["εἰσί(ν)", "ἐστί(ν)", "ἰσχυρά", "ἡ εἰρήνη"],
		},
		{
			id: "cl1-17",
			type: "vocab",
			prompt: "ὁ ποταμός",
			answer: "rivier",
			direction: "el->nl",
			hint: "uitspraak: ho potamos",
		},
		{
			id: "cl1-18",
			type: "vocab",
			prompt: "rivier",
			answer: "ὁ ποταμός",
			direction: "nl->el",
			options: ["ὁ ποταμός", "ἡ θάλαττα", "ἡ πέτρα", "τὸ δένδρον"],
		},
		{
			id: "cl1-19",
			type: "vocab",
			prompt: "οὐδέ",
			answer: "en niet, ook niet",
			alternatives: ["en niet", "ook niet"],
			direction: "el->nl",
			hint: "uitspraak: oudè • voor klinker verkort tot οὐδ'",
		},
		{
			id: "cl1-20",
			type: "vocab",
			prompt: "en niet, ook niet",
			answer: "οὐδέ",
			direction: "nl->el",
			options: ["οὐδέ", "οὐ", "δέ", "οὐκ"],
		},
		{
			id: "cl1-21",
			type: "vocab",
			prompt: "ἡ πέτρα",
			answer: "rots, rotsblok",
			alternatives: ["rots", "rotsblok"],
			direction: "el->nl",
			hint: "uitspraak: hè petra",
		},
		{
			id: "cl1-22",
			type: "vocab",
			prompt: "rots, rotsblok",
			answer: "ἡ πέτρα",
			direction: "nl->el",
			options: ["ἡ πέτρα", "ἡ γῆ", "τὸ δένδρον", "ἡ μάχη"],
		},
		{
			id: "cl1-23",
			type: "vocab",
			prompt: "τὸ δένδρον",
			answer: "boom",
			direction: "el->nl",
			hint: "uitspraak: to dendron",
		},
		{
			id: "cl1-24",
			type: "vocab",
			prompt: "boom",
			answer: "τὸ δένδρον",
			direction: "nl->el",
			options: ["τὸ δένδρον", "τὸ ζῷον", "τὸ ἔργον", "τὸ ἀργύριον"],
		},
		{
			id: "cl1-25",
			type: "vocab",
			prompt: "τὸ ζῷον",
			answer: "levend wezen",
			direction: "el->nl",
			hint: "uitspraak: to zōion",
		},
		{
			id: "cl1-26",
			type: "vocab",
			prompt: "levend wezen",
			answer: "τὸ ζῷον",
			direction: "nl->el",
			options: ["τὸ ζῷον", "ὁ ἄνθρωπος", "τὸ δένδρον", "ὁ θεός"],
		},
		{
			id: "cl1-27",
			type: "vocab",
			prompt: "ὁ ἄνθρωπος",
			answer: "mens",
			direction: "el->nl",
			hint: "uitspraak: ho anthrōpos",
		},
		{
			id: "cl1-28",
			type: "vocab",
			prompt: "mens",
			answer: "ὁ ἄνθρωπος",
			direction: "nl->el",
			options: ["ὁ ἄνθρωπος", "ὁ θεός", "τὸ ζῷον", "ἡ εἰρήνη"],
		},
		{
			id: "cl1-29",
			type: "vocab",
			prompt: "ὁ θεός",
			answer: "god",
			direction: "el->nl",
			hint: "uitspraak: ho theos",
		},
		{
			id: "cl1-30",
			type: "vocab",
			prompt: "god",
			answer: "ὁ θεός",
			direction: "nl->el",
			options: ["ὁ θεός", "ὁ ἄνθρωπος", "ὁ πόλεμος", "τὸ Χάος"],
		},
		{
			id: "cl1-31",
			type: "vocab",
			prompt: "ἡ μάχη",
			answer: "strijd, gevecht",
			alternatives: ["strijd", "gevecht"],
			direction: "el->nl",
			hint: "uitspraak: hè machè (ch als in ‘lach’)",
		},
		{
			id: "cl1-32",
			type: "vocab",
			prompt: "strijd, gevecht",
			answer: "ἡ μάχη",
			direction: "nl->el",
			options: ["ἡ μάχη", "ὁ πόλεμος", "ἡ πέτρα", "ἡ εἰρήνη"],
		},
		{
			id: "cl1-33",
			type: "vocab",
			prompt: "ὁ πόλεμος",
			answer: "oorlog",
			direction: "el->nl",
			hint: "uitspraak: ho polemos",
		},
		{
			id: "cl1-34",
			type: "vocab",
			prompt: "oorlog",
			answer: "ὁ πόλεμος",
			direction: "nl->el",
			options: ["ὁ πόλεμος", "ἡ μάχη", "ἡ εἰρήνη", "ὁ θεός"],
		},
		{
			id: "cl1-35",
			type: "vocab",
			prompt: "ἡ εἰρήνη",
			answer: "vrede",
			direction: "el->nl",
			hint: "uitspraak: hè eirènè",
		},
		{
			id: "cl1-36",
			type: "vocab",
			prompt: "vrede",
			answer: "ἡ εἰρήνη",
			direction: "nl->el",
			options: ["ἡ εἰρήνη", "ὁ πόλεμος", "ἡ μάχη", "ἡ σχολή"],
		},
		{
			id: "cl1-37",
			type: "vocab",
			prompt: "τὸ ἀργύριον",
			answer: "geld",
			direction: "el->nl",
			hint: "uitspraak: to argyrion",
		},
		{
			id: "cl1-38",
			type: "vocab",
			prompt: "geld",
			answer: "τὸ ἀργύριον",
			direction: "nl->el",
			options: ["τὸ ἀργύριον", "τὸ ἔργον", "τὸ δένδρον", "τὸ ζῷον"],
		},
		{
			id: "cl1-39",
			type: "vocab",
			prompt: "τὸ ἔργον",
			answer: "werk, taak, daad",
			alternatives: ["werk", "taak", "daad"],
			direction: "el->nl",
			hint: "uitspraak: to ergon • 1 werk, taak | 2 daad",
		},
		{
			id: "cl1-40",
			type: "vocab",
			prompt: "werk, taak, daad",
			answer: "τὸ ἔργον",
			direction: "nl->el",
			options: ["τὸ ἔργον", "τὸ ἀργύριον", "ἡ σχολή", "πρῶτον"],
		},
		{
			id: "cl1-41",
			type: "vocab",
			prompt: "ἡ σχολή",
			answer: "vrije tijd",
			direction: "el->nl",
			hint: "uitspraak: hè scholè • ons woord ‘school’ komt hiervandaan!",
		},
		{
			id: "cl1-42",
			type: "vocab",
			prompt: "vrije tijd",
			answer: "ἡ σχολή",
			direction: "nl->el",
			options: ["ἡ σχολή", "ἡ εἰρήνη", "τὸ ἔργον", "ἡ γῆ"],
		},
		{
			id: "cl1-43",
			type: "vocab",
			prompt: "πρῶτον",
			answer: "eerst",
			direction: "el->nl",
			hint: "uitspraak: prōton • bijwoord",
		},
		{
			id: "cl1-44",
			type: "vocab",
			prompt: "eerst (bijwoord)",
			answer: "πρῶτον",
			direction: "nl->el",
			options: ["πρῶτον", "ἐν ἀρχῇ", "ἰσχυρά", "οὐδέ"],
		},
		{
			id: "cl1-45",
			type: "vocab",
			prompt: "δέ",
			answer: "en, maar",
			alternatives: ["en", "maar"],
			direction: "el->nl",
			hint: "uitspraak: de • voor klinker verkort tot δ’ • staat nooit vooraan in de zin",
		},
		{
			id: "cl1-46",
			type: "vocab",
			prompt: "en, maar",
			answer: "δέ",
			direction: "nl->el",
			options: ["δέ", "οὐδέ", "οὐ", "ἐστί(ν)"],
		},
		{
			id: "cl1-47",
			type: "vocab",
			prompt: "ἰσχυρά",
			answer: "sterke, krachtige",
			alternatives: ["sterke", "krachtige"],
			direction: "el->nl",
			hint: "uitspraak: ischyra • vrouwelijk bijvoeglijk naamwoord",
		},
		{
			id: "cl1-48",
			type: "vocab",
			prompt: "sterke, krachtige",
			answer: "ἰσχυρά",
			direction: "nl->el",
			options: ["ἰσχυρά", "πρῶτον", "ἡ πέτρα", "εἰσί(ν)"],
		},
		// Extra: vormen van de ontkenning en δέ herkennen
		{
			id: "cl1-49",
			type: "vocab",
			prompt: "οὐκ (voor klinker)",
			answer: "niet",
			direction: "el->nl",
			hint: "uitspraak: ouk • vorm van οὐ voor een klinker",
		},
		{
			id: "cl1-50",
			type: "vocab",
			prompt: "οὐχ (voor klinker met ruwe geest)",
			answer: "niet",
			direction: "el->nl",
			hint: "uitspraak: ouch • vorm van οὐ voor een klinker met ruwe geest (bijv. ὁ)",
		},
		{
			id: "cl1-51",
			type: "vocab",
			prompt: "δ’ (verkort voor klinker)",
			answer: "en, maar",
			alternatives: ["en", "maar"],
			direction: "el->nl",
			hint: "uitspraak: d’ • verkorte vorm van δέ",
		},
		{
			id: "cl1-52",
			type: "vocab",
			prompt: "niet (voor medeklinker / werkwoord met ν)",
			answer: "οὐ",
			direction: "nl->el",
			hint: "Basisvorm; οὐκ voor klinker, οὐχ voor klinker met ruwe geest",
			options: ["οὐ", "οὐκ", "οὐχ", "οὐδέ"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
