import { type Chapter, chapterSchema } from "@/lib/schema";

// Les 2: transliteratie – Griekse woorden lezen en in Latijnse letters schrijven.
// Richting el->nl: het antwoord is de transliteratie (Latijns schrift),
// de hint geeft de Nederlandse betekenis + uitspraak.
// Er is bewust geen Griekse invoerbalk nodig: je typt alleen Latijnse letters.

const rawChapter = {
	id: "greek-transliteratie",
	title: "Ελληνικά – Transliteratie: van Grieks naar Latijns schrift",
	description:
		"Lees Griekse woorden en schrijf ze in Latijnse letters (bijv. νερό → nero). De hint vertelt wat het betekent en hoe je het uitspreekt.",
	language: "greek",
	exercises: [
		{
			id: "trans-1",
			type: "vocab",
			prompt: "γεια",
			answer: "geia",
			alternatives: ["yia", "gia"],
			direction: "el->nl",
			hint: "betekent: hallo • uitspraak: ‘ya’",
		},
		{
			id: "trans-2",
			type: "vocab",
			prompt: "γεια σου",
			answer: "geia sou",
			alternatives: ["yia sou", "gia sou", "geia su"],
			direction: "el->nl",
			hint: "betekent: hallo (informeel) • letterlijk: ‘gezondheid voor jou’",
		},
		{
			id: "trans-3",
			type: "vocab",
			prompt: "ναι",
			answer: "nai",
			alternatives: ["ne"],
			direction: "el->nl",
			hint: "betekent: ja • uitspraak: ‘ne’ (ai klinkt als e!)",
			options: ["nai", "ochi", "nero", "kala"],
		},
		{
			id: "trans-4",
			type: "vocab",
			prompt: "όχι",
			answer: "ochi",
			alternatives: ["ohi", "okhi"],
			direction: "el->nl",
			hint: "betekent: nee • uitspraak: ‘ochi’ (ch als in ‘lach’)",
		},
		{
			id: "trans-5",
			type: "vocab",
			prompt: "νερό",
			answer: "nero",
			direction: "el->nl",
			hint: "betekent: water • uitspraak: ‘nero’",
			options: ["nero", "krasi", "psomi", "spiti"],
		},
		{
			id: "trans-6",
			type: "vocab",
			prompt: "ψωμί",
			answer: "psomi",
			direction: "el->nl",
			hint: "betekent: brood • ψ = ps",
		},
		{
			id: "trans-7",
			type: "vocab",
			prompt: "το σπίτι",
			answer: "to spiti",
			alternatives: ["spiti"],
			direction: "el->nl",
			hint: "betekent: het huis • uitspraak: ‘spietie’",
		},
		{
			id: "trans-8",
			type: "vocab",
			prompt: "καλημέρα",
			answer: "kalimera",
			alternatives: ["kali mera"],
			direction: "el->nl",
			hint: "betekent: goedemorgen • letterlijk: ‘goede dag’",
		},
		{
			id: "trans-9",
			type: "vocab",
			prompt: "καλησπέρα",
			answer: "kalispera",
			alternatives: ["kali spera"],
			direction: "el->nl",
			hint: "betekent: goedenavond",
			options: ["kalispera", "kalimera", "kalinychta", "efcharisto"],
		},
		{
			id: "trans-10",
			type: "vocab",
			prompt: "ευχαριστώ",
			answer: "efcharisto",
			alternatives: ["evcharisto", "efharisto", "efcharisto poly"],
			direction: "el->nl",
			hint: "betekent: dank je • ευ = ef (voor klinkers: ev)",
		},
		{
			id: "trans-11",
			type: "vocab",
			prompt: "παρακαλώ",
			answer: "parakalo",
			direction: "el->nl",
			hint: "betekent: alstublieft / graag gedaan",
		},
		{
			id: "trans-12",
			type: "vocab",
			prompt: "φίλος",
			answer: "filos",
			direction: "el->nl",
			hint: "betekent: vriend • φ = f",
			options: ["filos", "fili", "polis", "chora"],
		},
		{
			id: "trans-13",
			type: "vocab",
			prompt: "θάλασσα",
			answer: "thalassa",
			alternatives: ["talassa"],
			direction: "el->nl",
			hint: "betekent: zee • θ = th",
		},
		{
			id: "trans-14",
			type: "vocab",
			prompt: "κρασί",
			answer: "krasi",
			direction: "el->nl",
			hint: "betekent: wijn",
		},
		{
			id: "trans-15",
			type: "vocab",
			prompt: "καφές",
			answer: "kafes",
			alternatives: ["cafes"],
			direction: "el->nl",
			hint: "betekent: koffie • uitspraak: ‘ka-fes’",
			options: ["kafes", "krasi", "nero", "gala"],
		},
		{
			id: "trans-16",
			type: "vocab",
			prompt: "αγάπη",
			answer: "agapi",
			direction: "el->nl",
			hint: "betekent: liefde",
		},
		{
			id: "trans-17",
			type: "vocab",
			prompt: "πόλη",
			answer: "poli",
			alternatives: ["polē"],
			direction: "el->nl",
			hint: "betekent: stad • η klinkt als i",
		},
		{
			id: "trans-18",
			type: "vocab",
			prompt: "σχολείο",
			answer: "scholeio",
			alternatives: ["scholio", "sxoleio"],
			direction: "el->nl",
			hint: "betekent: school • uitspraak: ‘scholio’",
		},
		{
			id: "trans-19",
			type: "vocab",
			prompt: "βιβλίο",
			answer: "vivlio",
			alternatives: ["biblio"],
			direction: "el->nl",
			hint: "betekent: boek • β klinkt als v, uitspraak: ‘vivlio’",
			options: ["vivlio", "vivlia", "vivlos", "grafio"],
		},
		{
			id: "trans-20",
			type: "vocab",
			prompt: "άνθρωπος",
			answer: "anthropos",
			alternatives: ["antropos"],
			direction: "el->nl",
			hint: "betekent: mens • θ = th, ω = o",
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
