import { type Chapter, chapterSchema } from "@/lib/schema";

export const rawChapter = {
	id: "minerva-2b",
	title: "Minerva – Woorden 2B (Midas en Pan)",
	description: "Woordenschat en grammatica op basis van paragraaf 2B met voorbeeldzinnen.",
	exercises: [
		{
			id: "w2b-1",
			type: "vocab",
			prompt: "bos",
			answer: "silva",
			direction: "nl->la",
			options: ["silva", "mons", "deus", "victoria"],
		},
		{
			id: "w2b-2",
			type: "vocab",
			prompt: "(hij/zij/het) zwerft rond, dwaalt (bijv. 'De god dwaalt in het bos')",
			answer: "errat",
			direction: "nl->la",
			hint: "infinitivus: errare",
		},
		{
			id: "w2b-3",
			type: "vocab",
			prompt: "videt",
			answer: "(hij/zij/het) ziet",
			direction: "la->nl",
			options: [
				"(hij/zij/het) ziet",
				"(hij/zij/het) hoort",
				"(hij/zij/het) roept",
				"(hij/zij/het) geeft",
			],
		},
		{
			id: "w2b-4",
			type: "vocab",
			prompt: "god",
			answer: "deus",
			direction: "nl->la",
		},
		{
			id: "w2b-5",
			type: "vocab",
			prompt: "canit",
			answer: "(hij/zij/het) zingt / speelt",
			direction: "la->nl",
			options: [
				"(hij/zij/het) zingt / speelt",
				"(hij/zij/het) heeft",
				"(hij/zij/het) roept",
				"(zij) strijden",
			],
		},
		{
			id: "w2b-6",
			type: "vocab",
			prompt: "(zij) strijden (bijv. 'De goden strijden')",
			answer: "certant",
			direction: "nl->la",
			hint: "infinitivus: certare",
		},
		{
			id: "w2b-7",
			type: "vocab",
			prompt: "berg (bijv. 'Hij klimt op de berg')",
			answer: "mons",
			direction: "nl->la",
			hint: "accusativus singularis: montem",
		},
		{
			id: "w2b-8",
			type: "vocab",
			prompt: "audit",
			answer: "(hij/zij/het) hoort, luistert",
			direction: "la->nl",
			options: [
				"(hij/zij/het) hoort, luistert",
				"(hij/zij/het) ziet",
				"(hij/zij/het) roept",
				"(hij/zij/het) dwaalt",
			],
		},
		{
			id: "w2b-9",
			type: "vocab",
			prompt: "overwinning",
			answer: "victoria",
			direction: "nl->la",
		},
		{
			id: "w2b-10",
			type: "vocab",
			prompt: "dat",
			answer: "(hij/zij/het) geeft",
			direction: "la->nl",
			hint: "infinitivus: dare",
			options: [
				"(hij/zij/het) geeft",
				"(hij/zij/het) heeft",
				"(hij/zij/het) zingt",
				"(hij/zij/het) hoort",
			],
		},
		{
			id: "w2b-11",
			type: "vocab",
			prompt: "echter, maar",
			answer: "autem",
			direction: "nl->la",
		},
		{
			id: "w2b-12",
			type: "vocab",
			prompt: "clamat",
			answer: "(hij/zij/het) roept",
			direction: "la->nl",
			options: [
				"(hij/zij/het) roept",
				"(hij/zij/het) hoort",
				"(hij/zij/het) zingt",
				"(zij) strijden",
			],
		},
		{
			id: "w2b-13",
			type: "vocab",
			prompt: "overwinnaar (bijv. 'De koning ziet de overwinnaar')",
			answer: "victor",
			direction: "nl->la",
			hint: "accusativus singularis: victorem",
		},
		{
			id: "w2b-14",
			type: "vocab",
			prompt: "dom, stom, dwaas (mannelijk: bijv. 'De dwaze koning')",
			answer: "stultus",
			direction: "nl->la",
		},
		{
			id: "w2b-15",
			type: "vocab",
			prompt: "habet",
			answer: "(hij/zij/het) heeft, houdt",
			direction: "la->nl",
			options: [
				"(hij/zij/het) heeft, houdt",
				"(hij/zij/het) geeft",
				"(hij/zij/het) ziet",
				"(hij/zij/het) dwaalt",
			],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
