import { type Chapter, chapterSchema } from "@/lib/schema";

export const rawChapter = {
	id: "minerva-2a",
	title: "Minerva – Woordenlijst 2a",
	description: "Woorden 2A Een geschenk voor Midas",
	exercises: [
		{
			id: "ex1",
			type: "vocab",
			prompt: "wonderbaarlijk, schitterend",
			answer: "mirus, -a, -um",
			alternatives: ["mirus", "mira", "mirum"],
			direction: "nl->la",
		},
		{
			id: "ex2",
			type: "vocab",
			prompt: "mirus, -a, -um",
			answer: "wonderbaarlijk, schitterend",
			direction: "la->nl",
			options: [
				"wonderbaarlijk, schitterend",
				"blij, vrolijk, opgewekt",
				"groot",
				"klein",
			],
		},
		{
			id: "ex3",
			type: "vocab",
			prompt: "geschenk",
			answer: "donum",
			direction: "nl->la",
		},
		{
			id: "ex4",
			type: "vocab",
			prompt: "donum",
			answer: "geschenk",
			direction: "la->nl",
			options: ["geschenk", "paleis", "koning", "wijn"],
		},
		{
			id: "ex5",
			type: "vocab",
			prompt: "ontvangt, krijgt",
			answer: "accipit",
			direction: "nl->la",
		},
		{
			id: "ex6",
			type: "vocab",
			prompt: "accipit",
			answer: "ontvangt, krijgt",
			alternatives: [
				"hij ontvangt",
				"zij ontvangt",
				"het ontvangt",
				"hij krijgt",
				"zij krijgt",
				"het krijgt",
			],
			direction: "la->nl",
			options: ["ontvangt, krijgt", "houdt van, bemint", "rent", "verandert"],
		},
		{
			id: "ex7",
			type: "vocab",
			prompt: "houdt van, bemint",
			answer: "amat",
			direction: "nl->la",
		},
		{
			id: "ex8",
			type: "vocab",
			prompt: "amat",
			answer: "houdt van, bemint",
			alternatives: [
				"hij houdt van",
				"zij houdt van",
				"het houdt van",
				"hij bemint",
				"zij bemint",
				"het bemint",
			],
			direction: "la->nl",
			options: ["houdt van, bemint", "ontvangt, krijgt", "raakt aan", "begint"],
		},
		{
			id: "ex9",
			type: "vocab",
			prompt: "koning",
			answer: "rex",
			direction: "nl->la",
			hint: "accusativus: regem",
		},
		{
			id: "ex10",
			type: "vocab",
			prompt: "rex",
			answer: "koning",
			direction: "la->nl",
			options: ["koning", "slaaf", "paleis", "geschenk"],
		},
		{
			id: "ex11",
			type: "vocab",
			prompt: "blij, vrolijk, opgewekt",
			answer: "laetus, -a, -um",
			alternatives: ["laetus", "laeta", "laetum"],
			direction: "nl->la",
		},
		{
			id: "ex12",
			type: "vocab",
			prompt: "laetus, -a, -um",
			answer: "blij, vrolijk, opgewekt",
			direction: "la->nl",
			options: [
				"blij, vrolijk, opgewekt",
				"wonderbaarlijk, schitterend",
				"groot",
				"moe",
			],
		},
		{
			id: "ex13",
			type: "vocab",
			prompt: "is",
			answer: "est",
			direction: "nl->la",
		},
		{
			id: "ex14",
			type: "vocab",
			prompt: "est",
			answer: "is",
			direction: "la->nl",
			options: ["is", "en", "ook", "nu"],
		},
		{
			id: "ex15",
			type: "vocab",
			prompt: "en / ook",
			answer: "et",
			direction: "nl->la",
		},
		{
			id: "ex16",
			type: "vocab",
			prompt: "door ... heen / gedurende (+ acc.)",
			answer: "per",
			direction: "nl->la",
		},
		{
			id: "ex17",
			type: "vocab",
			prompt: "per + acc.",
			answer: "door ... heen / gedurende",
			direction: "la->nl",
			options: ["door ... heen / gedurende", "naar, naar binnen", "in", "met"],
		},
		{
			id: "ex18",
			type: "vocab",
			prompt: "paleis",
			answer: "regia",
			direction: "nl->la",
		},
		{
			id: "ex19",
			type: "vocab",
			prompt: "regia",
			answer: "paleis",
			direction: "la->nl",
			options: ["paleis", "tafel", "koning", "aarde"],
		},
		{
			id: "ex20",
			type: "vocab",
			prompt: "rent",
			answer: "currit",
			direction: "nl->la",
		},
		{
			id: "ex21",
			type: "vocab",
			prompt: "currit",
			answer: "rent",
			alternatives: ["hij rent", "zij rent", "het rent"],
			direction: "la->nl",
			options: ["rent", "begint", "raakt aan", "verandert"],
		},
		{
			id: "ex22",
			type: "vocab",
			prompt: "nu",
			answer: "nunc",
			direction: "nl->la",
		},
		{
			id: "ex23",
			type: "vocab",
			prompt: "nunc",
			answer: "nu",
			direction: "la->nl",
			options: ["nu", "meteen", "ook", "en"],
		},
		{
			id: "ex24",
			type: "vocab",
			prompt: "tafel",
			answer: "mensa",
			direction: "nl->la",
		},
		{
			id: "ex25",
			type: "vocab",
			prompt: "mensa",
			answer: "tafel",
			direction: "la->nl",
			options: ["tafel", "voedsel", "wijn", "paleis"],
		},
		{
			id: "ex26",
			type: "vocab",
			prompt: "raakt aan",
			answer: "tangit",
			direction: "nl->la",
		},
		{
			id: "ex27",
			type: "vocab",
			prompt: "tangit",
			answer: "raakt aan",
			alternatives: ["hij raakt aan", "zij raakt aan", "het raakt aan"],
			direction: "la->nl",
			options: ["raakt aan", "verandert", "ontvangt", "rent"],
		},
		{
			id: "ex28",
			type: "vocab",
			prompt: "ook",
			answer: "quoque",
			direction: "nl->la",
		},
		{
			id: "ex29",
			type: "vocab",
			prompt: "quoque",
			answer: "ook",
			direction: "la->nl",
			options: ["ook", "nu", "meteen", "en"],
		},
		{
			id: "ex30",
			type: "vocab",
			prompt: "naar, naar binnen / in (+ acc.)",
			answer: "in",
			direction: "nl->la",
		},
		{
			id: "ex31",
			type: "vocab",
			prompt: "in + acc.",
			answer: "naar, naar binnen / in",
			direction: "la->nl",
			options: ["naar, naar binnen / in", "door ... heen", "uit", "met"],
		},
		{
			id: "ex32",
			type: "vocab",
			prompt: "goud",
			answer: "aurum",
			direction: "nl->la",
		},
		{
			id: "ex33",
			type: "vocab",
			prompt: "aurum",
			answer: "goud",
			direction: "la->nl",
			options: ["goud", "wijn", "geschenk", "voedsel"],
		},
		{
			id: "ex34",
			type: "vocab",
			prompt: "verandert, verwisselt",
			answer: "mutat",
			direction: "nl->la",
		},
		{
			id: "ex35",
			type: "vocab",
			prompt: "mutat",
			answer: "verandert, verwisselt",
			alternatives: [
				"hij verandert",
				"zij verandert",
				"het verandert",
				"hij verwisselt",
				"zij verwisselt",
				"het verwisselt",
			],
			direction: "la->nl",
			options: ["verandert, verwisselt", "raakt aan", "begint", "houdt van"],
		},
		{
			id: "ex36",
			type: "vocab",
			prompt: "slaaf",
			answer: "servus",
			direction: "nl->la",
		},
		{
			id: "ex37",
			type: "vocab",
			prompt: "servus",
			answer: "slaaf",
			direction: "la->nl",
			options: ["slaaf", "koning", "vriend", "jongen"],
		},
		{
			id: "ex38",
			type: "vocab",
			prompt: "voedsel, eten",
			answer: "cibus",
			direction: "nl->la",
		},
		{
			id: "ex39",
			type: "vocab",
			prompt: "cibus",
			answer: "voedsel, eten",
			direction: "la->nl",
			options: ["voedsel, eten", "wijn", "tafel", "goud"],
		},
		{
			id: "ex40",
			type: "vocab",
			prompt: "wijn",
			answer: "vinum",
			direction: "nl->la",
		},
		{
			id: "ex41",
			type: "vocab",
			prompt: "vinum",
			answer: "wijn",
			direction: "la->nl",
			options: ["wijn", "voedsel", "goud", "geschenk"],
		},
		{
			id: "ex42",
			type: "vocab",
			prompt: "begint",
			answer: "incipit",
			direction: "nl->la",
		},
		{
			id: "ex43",
			type: "vocab",
			prompt: "incipit",
			answer: "begint",
			alternatives: ["hij begint", "zij begint", "het begint"],
			direction: "la->nl",
			options: ["begint", "rent", "verandert", "raakt aan"],
		},
		{
			id: "ex44",
			type: "vocab",
			prompt: "meteen",
			answer: "statim",
			direction: "nl->la",
		},
		{
			id: "ex45",
			type: "vocab",
			prompt: "statim",
			answer: "meteen",
			direction: "la->nl",
			options: ["meteen", "nu", "ook", "snel"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
