import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-1",
	title: "Français – Débutant 1 : Bonjour !",
	description:
		"Kennismaken, begroetingen en alledaagse woorden. Oefen met accenten (é è ê ë ç).",
	language: "french",
	exercises: [
		{
			id: "fr1-1",
			type: "vocab",
			prompt: "hallo / goedendag",
			answer: "bonjour",
			direction: "nl->fr",
			hint: "Begroeting overdag",
		},
		{
			id: "fr1-2",
			type: "vocab",
			prompt: "bonjour",
			answer: "hallo, goedendag",
			alternatives: ["hallo", "goedendag"],
			direction: "fr->nl",
			options: ["hallo, goedendag", "tot ziens", "dank je", "ja"],
		},
		{
			id: "fr1-3",
			type: "vocab",
			prompt: "dank je / bedankt",
			answer: "merci",
			direction: "nl->fr",
		},
		{
			id: "fr1-4",
			type: "vocab",
			prompt: "merci",
			answer: "dank je, bedankt",
			alternatives: ["dank je", "bedankt"],
			direction: "fr->nl",
			options: ["dank je, bedankt", "alstublieft", "hallo", "nee"],
		},
		{
			id: "fr1-5",
			type: "vocab",
			prompt: "ja",
			answer: "oui",
			direction: "nl->fr",
			options: ["oui", "non", "merci", "bonjour"],
		},
		{
			id: "fr1-6",
			type: "vocab",
			prompt: "nee",
			answer: "non",
			direction: "nl->fr",
			options: ["oui", "non", "si", "mais"],
		},
		{
			id: "fr1-7",
			type: "vocab",
			prompt: "het huis",
			answer: "la maison",
			direction: "nl->fr",
			hint: "Let op: la (vrouwelijk)",
		},
		{
			id: "fr1-8",
			type: "vocab",
			prompt: "la maison",
			answer: "het huis",
			direction: "fr->nl",
			options: ["het huis", "de tafel", "de stoel", "het water"],
		},
		{
			id: "fr1-9",
			type: "vocab",
			prompt: "water",
			answer: "l'eau",
			direction: "nl->fr",
			hint: "eau met apostrof, vrouwelijk. Let op l' + eau",
		},
		{
			id: "fr1-10",
			type: "vocab",
			prompt: "ster",
			answer: "étoile",
			direction: "nl->fr",
			hint: "Let op accent aigu: é",
		},
		{
			id: "fr1-11",
			type: "declension",
			prompt: "être – ik ben (1e persoon enkelvoud, tegenwoordige tijd)",
			lemma: "être – zijn",
			form: "je ...",
			answer: "je suis",
			alternatives: ["suis"],
			hint: "je suis, tu es, il/elle est",
			options: ["je suis", "j'ai", "je vais", "je fais"],
		},
		{
			id: "fr1-12",
			type: "declension",
			prompt: "avoir – wij hebben (1e persoon meervoud)",
			lemma: "avoir – hebben",
			form: "nous ...",
			answer: "nous avons",
			alternatives: ["avons"],
			hint: "avoir: j'ai, tu as, il a, nous avons, vous avez, ils ont",
		},
		{
			id: "fr1-13",
			type: "vocab",
			prompt: "alstublieft / alsjeblieft",
			answer: "s'il vous plaît",
			direction: "nl->fr",
			hint: "Let op apostrof en accent circonflexe: î",
		},
		{
			id: "fr1-14",
			type: "vocab",
			prompt: "au revoir",
			answer: "tot ziens",
			direction: "fr->nl",
			options: ["tot ziens", "hallo", "welterusten", "dank je"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
