import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-1",
	title: "Français – Débutant 1 : Les jours et les nombres (1–20)",
	description:
		"De dagen van de week en de getallen 1 tot 20. Oefen woordenschat Nederlands ↔ Frans.",
	language: "french",
	exercises: [
		// --- Les jours de la semaine (7) ---
		{
			id: "fr1-1",
			type: "vocab",
			prompt: "maandag",
			answer: "lundi",
			direction: "nl->fr",
			hint: "Lundi – de dag van de maan (lune)",
		},
		{
			id: "fr1-2",
			type: "vocab",
			prompt: "mardi",
			answer: "dinsdag",
			direction: "fr->nl",
			options: ["dinsdag", "maandag", "woensdag", "donderdag"],
		},
		{
			id: "fr1-3",
			type: "vocab",
			prompt: "woensdag",
			answer: "mercredi",
			direction: "nl->fr",
			hint: "Mercredi – dag van Mercurius",
		},
		{
			id: "fr1-4",
			type: "vocab",
			prompt: "jeudi",
			answer: "donderdag",
			direction: "fr->nl",
			options: ["donderdag", "vrijdag", "woensdag", "zaterdag"],
		},
		{
			id: "fr1-5",
			type: "vocab",
			prompt: "vrijdag",
			answer: "vendredi",
			direction: "nl->fr",
			hint: "Vendredi – dag van Venus",
		},
		{
			id: "fr1-6",
			type: "vocab",
			prompt: "samedi",
			answer: "zaterdag",
			direction: "fr->nl",
			options: ["zaterdag", "zondag", "vrijdag", "maandag"],
		},
		{
			id: "fr1-7",
			type: "vocab",
			prompt: "zondag",
			answer: "dimanche",
			direction: "nl->fr",
			hint: "Dimanche – van het Latijn dies dominica",
		},
		// --- Les nombres 1–20 (20) ---
		{
			id: "fr1-8",
			type: "vocab",
			prompt: "één / 1",
			answer: "un",
			direction: "nl->fr",
			options: ["un", "une", "deux", "trois"],
		},
		{
			id: "fr1-9",
			type: "vocab",
			prompt: "deux",
			answer: "twee, 2",
			alternatives: ["twee", "2"],
			direction: "fr->nl",
			options: ["twee, 2", "één, 1", "drie, 3", "vier, 4"],
		},
		{
			id: "fr1-10",
			type: "vocab",
			prompt: "drie / 3",
			answer: "trois",
			direction: "nl->fr",
		},
		{
			id: "fr1-11",
			type: "vocab",
			prompt: "quatre",
			answer: "vier, 4",
			alternatives: ["vier", "4"],
			direction: "fr->nl",
			options: ["vier, 4", "vijf, 5", "drie, 3", "twee, 2"],
		},
		{
			id: "fr1-12",
			type: "vocab",
			prompt: "vijf / 5",
			answer: "cinq",
			direction: "nl->fr",
		},
		{
			id: "fr1-13",
			type: "vocab",
			prompt: "six",
			answer: "zes, 6",
			alternatives: ["zes", "6"],
			direction: "fr->nl",
			options: ["zes, 6", "zeven, 7", "vijf, 5", "acht, 8"],
		},
		{
			id: "fr1-14",
			type: "vocab",
			prompt: "zeven / 7",
			answer: "sept",
			direction: "nl->fr",
		},
		{
			id: "fr1-15",
			type: "vocab",
			prompt: "huit",
			answer: "acht, 8",
			alternatives: ["acht", "8"],
			direction: "fr->nl",
			options: ["acht, 8", "zeven, 7", "negen, 9", "tien, 10"],
		},
		{
			id: "fr1-16",
			type: "vocab",
			prompt: "negen / 9",
			answer: "neuf",
			direction: "nl->fr",
		},
		{
			id: "fr1-17",
			type: "vocab",
			prompt: "dix",
			answer: "tien, 10",
			alternatives: ["tien", "10"],
			direction: "fr->nl",
			options: ["tien, 10", "negen, 9", "elf, 11", "twaalf, 12"],
		},
		{
			id: "fr1-18",
			type: "vocab",
			prompt: "elf / 11",
			answer: "onze",
			direction: "nl->fr",
		},
		{
			id: "fr1-19",
			type: "vocab",
			prompt: "douze",
			answer: "twaalf, 12",
			alternatives: ["twaalf", "12"],
			direction: "fr->nl",
			options: ["twaalf, 12", "elf, 11", "dertien, 13", "veertien, 14"],
		},
		{
			id: "fr1-20",
			type: "vocab",
			prompt: "dertien / 13",
			answer: "treize",
			direction: "nl->fr",
		},
		{
			id: "fr1-21",
			type: "vocab",
			prompt: "quatorze",
			answer: "veertien, 14",
			alternatives: ["veertien", "14"],
			direction: "fr->nl",
			options: ["veertien, 14", "dertien, 13", "vijftien, 15", "zestien, 16"],
		},
		{
			id: "fr1-22",
			type: "vocab",
			prompt: "vijftien / 15",
			answer: "quinze",
			direction: "nl->fr",
		},
		{
			id: "fr1-23",
			type: "vocab",
			prompt: "seize",
			answer: "zestien, 16",
			alternatives: ["zestien", "16"],
			direction: "fr->nl",
			options: ["zestien, 16", "vijftien, 15", "zeventien, 17", "achttien, 18"],
		},
		{
			id: "fr1-24",
			type: "vocab",
			prompt: "zeventien / 17",
			answer: "dix-sept",
			direction: "nl->fr",
			hint: "10 + 7 : dix-sept (met koppelteken)",
		},
		{
			id: "fr1-25",
			type: "vocab",
			prompt: "dix-huit",
			answer: "achttien, 18",
			alternatives: ["achttien", "18"],
			direction: "fr->nl",
			options: [
				"achttien, 18",
				"zeventien, 17",
				"negentien, 19",
				"twintig, 20",
			],
			hint: "10 + 8 : dix-huit",
		},
		{
			id: "fr1-26",
			type: "vocab",
			prompt: "negentien / 19",
			answer: "dix-neuf",
			direction: "nl->fr",
			hint: "10 + 9 : dix-neuf",
		},
		{
			id: "fr1-27",
			type: "vocab",
			prompt: "vingt",
			answer: "twintig, 20",
			alternatives: ["twintig", "20"],
			direction: "fr->nl",
			options: ["twintig, 20", "negentien, 19", "achttien, 18", "tien, 10"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
