import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-jours",
	title: "Français – Les jours de la semaine",
	description:
		"De dagen van de week. Oefen woordenschat Nederlands ↔ Frans.",
	language: "french",
	exercises: [
		{
			id: "jours-1",
			type: "vocab",
			prompt: "maandag",
			answer: "lundi",
			direction: "nl->fr",
			hint: "Lundi – de dag van de maan (lune)",
		},
		{
			id: "jours-2",
			type: "vocab",
			prompt: "lundi",
			answer: "maandag",
			direction: "fr->nl",
			options: ["maandag", "dinsdag", "woensdag", "donderdag"],
		},
		{
			id: "jours-3",
			type: "vocab",
			prompt: "mardi",
			answer: "dinsdag",
			direction: "fr->nl",
			options: ["dinsdag", "maandag", "woensdag", "donderdag"],
		},
		{
			id: "jours-4",
			type: "vocab",
			prompt: "dinsdag",
			answer: "mardi",
			direction: "nl->fr",
			hint: "Mardi – dag van Mars",
		},
		{
			id: "jours-5",
			type: "vocab",
			prompt: "woensdag",
			answer: "mercredi",
			direction: "nl->fr",
			hint: "Mercredi – dag van Mercurius",
		},
		{
			id: "jours-6",
			type: "vocab",
			prompt: "mercredi",
			answer: "woensdag",
			direction: "fr->nl",
			options: ["woensdag", "dinsdag", "donderdag", "vrijdag"],
		},
		{
			id: "jours-7",
			type: "vocab",
			prompt: "jeudi",
			answer: "donderdag",
			direction: "fr->nl",
			options: ["donderdag", "vrijdag", "woensdag", "zaterdag"],
		},
		{
			id: "jours-8",
			type: "vocab",
			prompt: "donderdag",
			answer: "jeudi",
			direction: "nl->fr",
			hint: "Jeudi – dag van Jupiter",
		},
		{
			id: "jours-9",
			type: "vocab",
			prompt: "vrijdag",
			answer: "vendredi",
			direction: "nl->fr",
			hint: "Vendredi – dag van Venus",
		},
		{
			id: "jours-10",
			type: "vocab",
			prompt: "vendredi",
			answer: "vrijdag",
			direction: "fr->nl",
			options: ["vrijdag", "zaterdag", "donderdag", "zondag"],
		},
		{
			id: "jours-11",
			type: "vocab",
			prompt: "samedi",
			answer: "zaterdag",
			direction: "fr->nl",
			options: ["zaterdag", "zondag", "vrijdag", "maandag"],
		},
		{
			id: "jours-12",
			type: "vocab",
			prompt: "zaterdag",
			answer: "samedi",
			direction: "nl->fr",
			hint: "Samedi – dag van Saturnus",
		},
		{
			id: "jours-13",
			type: "vocab",
			prompt: "zondag",
			answer: "dimanche",
			direction: "nl->fr",
			hint: "Dimanche – van het Latijn dies dominica",
		},
		{
			id: "jours-14",
			type: "vocab",
			prompt: "dimanche",
			answer: "zondag",
			direction: "fr->nl",
			options: ["zondag", "zaterdag", "maandag", "vrijdag"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
