import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-nombres",
	title: "Français – Les nombres (1–20)",
	description:
		"De getallen 1 tot 20. Oefen woordenschat Nederlands ↔ Frans.",
	language: "french",
	exercises: [
		{
			id: "nombres-1",
			type: "vocab",
			prompt: "één / 1",
			answer: "un",
			direction: "nl->fr",
			options: ["un", "une", "deux", "trois"],
		},
		{
			id: "nombres-1r",
			type: "vocab",
			prompt: "un",
			answer: "één, 1",
			alternatives: ["één", "een", "1"],
			direction: "fr->nl",
		},
		{
			id: "nombres-2",
			type: "vocab",
			prompt: "deux",
			answer: "twee, 2",
			alternatives: ["twee", "2"],
			direction: "fr->nl",
			options: ["twee, 2", "één, 1", "drie, 3", "vier, 4"],
		},
		{
			id: "nombres-2r",
			type: "vocab",
			prompt: "twee / 2",
			answer: "deux",
			direction: "nl->fr",
		},
		{
			id: "nombres-3",
			type: "vocab",
			prompt: "drie / 3",
			answer: "trois",
			direction: "nl->fr",
		},
		{
			id: "nombres-3r",
			type: "vocab",
			prompt: "trois",
			answer: "drie, 3",
			alternatives: ["drie", "3"],
			direction: "fr->nl",
		},
		{
			id: "nombres-4",
			type: "vocab",
			prompt: "quatre",
			answer: "vier, 4",
			alternatives: ["vier", "4"],
			direction: "fr->nl",
			options: ["vier, 4", "vijf, 5", "drie, 3", "twee, 2"],
		},
		{
			id: "nombres-4r",
			type: "vocab",
			prompt: "vier / 4",
			answer: "quatre",
			direction: "nl->fr",
		},
		{
			id: "nombres-5",
			type: "vocab",
			prompt: "vijf / 5",
			answer: "cinq",
			direction: "nl->fr",
		},
		{
			id: "nombres-5r",
			type: "vocab",
			prompt: "cinq",
			answer: "vijf, 5",
			alternatives: ["vijf", "5"],
			direction: "fr->nl",
		},
		{
			id: "nombres-6",
			type: "vocab",
			prompt: "six",
			answer: "zes, 6",
			alternatives: ["zes", "6"],
			direction: "fr->nl",
			options: ["zes, 6", "zeven, 7", "vijf, 5", "acht, 8"],
		},
		{
			id: "nombres-6r",
			type: "vocab",
			prompt: "zes / 6",
			answer: "six",
			direction: "nl->fr",
		},
		{
			id: "nombres-7",
			type: "vocab",
			prompt: "zeven / 7",
			answer: "sept",
			direction: "nl->fr",
		},
		{
			id: "nombres-7r",
			type: "vocab",
			prompt: "sept",
			answer: "zeven, 7",
			alternatives: ["zeven", "7"],
			direction: "fr->nl",
		},
		{
			id: "nombres-8",
			type: "vocab",
			prompt: "huit",
			answer: "acht, 8",
			alternatives: ["acht", "8"],
			direction: "fr->nl",
			options: ["acht, 8", "zeven, 7", "negen, 9", "tien, 10"],
		},
		{
			id: "nombres-8r",
			type: "vocab",
			prompt: "acht / 8",
			answer: "huit",
			direction: "nl->fr",
			hint: "Let op de stomme h: huit (spreek uit als ‘wiet’)",
		},
		{
			id: "nombres-9",
			type: "vocab",
			prompt: "negen / 9",
			answer: "neuf",
			direction: "nl->fr",
		},
		{
			id: "nombres-9r",
			type: "vocab",
			prompt: "neuf",
			answer: "negen, 9",
			alternatives: ["negen", "9"],
			direction: "fr->nl",
		},
		{
			id: "nombres-10",
			type: "vocab",
			prompt: "dix",
			answer: "tien, 10",
			alternatives: ["tien", "10"],
			direction: "fr->nl",
			options: ["tien, 10", "negen, 9", "elf, 11", "twaalf, 12"],
		},
		{
			id: "nombres-10r",
			type: "vocab",
			prompt: "tien / 10",
			answer: "dix",
			direction: "nl->fr",
		},
		{
			id: "nombres-11",
			type: "vocab",
			prompt: "elf / 11",
			answer: "onze",
			direction: "nl->fr",
		},
		{
			id: "nombres-11r",
			type: "vocab",
			prompt: "onze",
			answer: "elf, 11",
			alternatives: ["elf", "11"],
			direction: "fr->nl",
			hint: "Let op: onze (11) is iets anders dan ‘ons’!",
		},
		{
			id: "nombres-12",
			type: "vocab",
			prompt: "douze",
			answer: "twaalf, 12",
			alternatives: ["twaalf", "12"],
			direction: "fr->nl",
			options: ["twaalf, 12", "elf, 11", "dertien, 13", "veertien, 14"],
		},
		{
			id: "nombres-12r",
			type: "vocab",
			prompt: "twaalf / 12",
			answer: "douze",
			direction: "nl->fr",
		},
		{
			id: "nombres-13",
			type: "vocab",
			prompt: "dertien / 13",
			answer: "treize",
			direction: "nl->fr",
		},
		{
			id: "nombres-13r",
			type: "vocab",
			prompt: "treize",
			answer: "dertien, 13",
			alternatives: ["dertien", "13"],
			direction: "fr->nl",
		},
		{
			id: "nombres-14",
			type: "vocab",
			prompt: "quatorze",
			answer: "veertien, 14",
			alternatives: ["veertien", "14"],
			direction: "fr->nl",
			options: ["veertien, 14", "dertien, 13", "vijftien, 15", "zestien, 16"],
		},
		{
			id: "nombres-14r",
			type: "vocab",
			prompt: "veertien / 14",
			answer: "quatorze",
			direction: "nl->fr",
		},
		{
			id: "nombres-15",
			type: "vocab",
			prompt: "vijftien / 15",
			answer: "quinze",
			direction: "nl->fr",
		},
		{
			id: "nombres-15r",
			type: "vocab",
			prompt: "quinze",
			answer: "vijftien, 15",
			alternatives: ["vijftien", "15"],
			direction: "fr->nl",
		},
		{
			id: "nombres-16",
			type: "vocab",
			prompt: "seize",
			answer: "zestien, 16",
			alternatives: ["zestien", "16"],
			direction: "fr->nl",
			options: ["zestien, 16", "vijftien, 15", "zeventien, 17", "achttien, 18"],
		},
		{
			id: "nombres-16r",
			type: "vocab",
			prompt: "zestien / 16",
			answer: "seize",
			direction: "nl->fr",
		},
		{
			id: "nombres-17",
			type: "vocab",
			prompt: "zeventien / 17",
			answer: "dix-sept",
			direction: "nl->fr",
			hint: "10 + 7 : dix-sept (met koppelteken)",
		},
		{
			id: "nombres-17r",
			type: "vocab",
			prompt: "dix-sept",
			answer: "zeventien, 17",
			alternatives: ["zeventien", "17"],
			direction: "fr->nl",
			hint: "10 + 7 : dix-sept",
		},
		{
			id: "nombres-18",
			type: "vocab",
			prompt: "dix-huit",
			answer: "achttien, 18",
			alternatives: ["achttien", "18"],
			direction: "fr->nl",
			options: [
				"achttien, 18",
				"zeventien, 17",
				"negentien, 19",
				"twintig, 20",
			],
			hint: "10 + 8 : dix-huit",
		},
		{
			id: "nombres-18r",
			type: "vocab",
			prompt: "achttien / 18",
			answer: "dix-huit",
			direction: "nl->fr",
			hint: "10 + 8 : dix-huit (met koppelteken)",
		},
		{
			id: "nombres-19",
			type: "vocab",
			prompt: "negentien / 19",
			answer: "dix-neuf",
			direction: "nl->fr",
			hint: "10 + 9 : dix-neuf",
		},
		{
			id: "nombres-19r",
			type: "vocab",
			prompt: "dix-neuf",
			answer: "negentien, 19",
			alternatives: ["negentien", "19"],
			direction: "fr->nl",
			hint: "10 + 9 : dix-neuf",
		},
		{
			id: "nombres-20",
			type: "vocab",
			prompt: "vingt",
			answer: "twintig, 20",
			alternatives: ["twintig", "20"],
			direction: "fr->nl",
			options: ["twintig, 20", "negentien, 19", "achttien, 18", "tien, 10"],
		},
		{
			id: "nombres-20r",
			type: "vocab",
			prompt: "twintig / 20",
			answer: "vingt",
			direction: "nl->fr",
			hint: "Let op: vingt eindigt op -gt (spreek uit als ‘vè’)",
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
