import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-vocabulaire-a",
	title: "Français – Apprendre vocabulaire A : les vacances",
	description:
		"Eerste woordenschat: vakantie, kennismaken en korte zinnetjes. Oefen woordenschat Nederlands ↔ Frans.",
	language: "french",
	exercises: [
		{
			id: "vocA-1",
			type: "vocab",
			prompt: "les vacances",
			answer: "de vakantie",
			direction: "fr->nl",
			hint: "vrouwelijk meervoud (v mv)",
		},
		{
			id: "vocA-2",
			type: "vocab",
			prompt: "de vakantie (vrouwelijk meervoud)",
			answer: "les vacances",
			direction: "nl->fr",
			options: ["les vacances", "le camping", "les vacance", "la vacances"],
		},
		{
			id: "vocA-3",
			type: "vocab",
			prompt: "de camping",
			answer: "le camping",
			direction: "nl->fr",
			hint: "mannelijk: le camping",
		},
		{
			id: "vocA-4",
			type: "vocab",
			prompt: "le camping",
			answer: "de camping",
			direction: "fr->nl",
			options: ["de camping", "de vakantie", "ik zoek", "hij is"],
		},
		{
			id: "vocA-5",
			type: "vocab",
			prompt: "il est",
			answer: "hij is",
			direction: "fr->nl",
		},
		{
			id: "vocA-6",
			type: "vocab",
			prompt: "hij is",
			answer: "il est",
			direction: "nl->fr",
			hint: "il = hij",
		},
		{
			id: "vocA-7",
			type: "vocab",
			prompt: "ik zoek",
			answer: "je cherche",
			direction: "nl->fr",
		},
		{
			id: "vocA-8",
			type: "vocab",
			prompt: "je cherche",
			answer: "ik zoek",
			direction: "fr->nl",
			options: ["ik zoek", "ik spreek", "ik ben", "hij is"],
		},
		{
			id: "vocA-9",
			type: "vocab",
			prompt: "voilà",
			answer: "alsjeblieft",
			direction: "fr->nl",
			hint: "als je iets gééft (bij vragen: s'il vous plaît)",
		},
		{
			id: "vocA-10",
			type: "vocab",
			prompt: "alsjeblieft (bij iets geven)",
			answer: "voilà",
			direction: "nl->fr",
			options: ["voilà", "merci", "de rien", "pardon"],
		},
		{
			id: "vocA-11",
			type: "vocab",
			prompt: "ik spreek / ik praat",
			answer: "je parle",
			direction: "nl->fr",
		},
		{
			id: "vocA-12",
			type: "vocab",
			prompt: "je parle",
			answer: "ik spreek, ik praat",
			alternatives: ["ik spreek", "ik praat"],
			direction: "fr->nl",
		},
		{
			id: "vocA-13",
			type: "vocab",
			prompt: "un peu",
			answer: "een beetje",
			direction: "fr->nl",
		},
		{
			id: "vocA-14",
			type: "vocab",
			prompt: "een beetje",
			answer: "un peu",
			direction: "nl->fr",
			options: ["un peu", "ici", "alors", "et"],
		},
		{
			id: "vocA-15",
			type: "vocab",
			prompt: "Frans (de taal)",
			answer: "français",
			direction: "nl->fr",
			hint: "let op de ç (cédille) – gebruik de accent-balk",
		},
		{
			id: "vocA-16",
			type: "vocab",
			prompt: "français",
			answer: "Frans",
			direction: "fr->nl",
			options: ["Frans", "Nederlands(e)", "hier", "dus"],
		},
		{
			id: "vocA-17",
			type: "vocab",
			prompt: "je suis",
			answer: "ik ben",
			direction: "fr->nl",
		},
		{
			id: "vocA-18",
			type: "vocab",
			prompt: "ik ben",
			answer: "je suis",
			direction: "nl->fr",
			hint: "être: je suis, il est",
		},
		{
			id: "vocA-19",
			type: "vocab",
			prompt: "Nederlands(e)",
			answer: "hollandais",
			alternatives: ["hollandaise"],
			direction: "nl->fr",
			hint: "mannelijk: hollandais, vrouwelijk: hollandaise",
		},
		{
			id: "vocA-20",
			type: "vocab",
			prompt: "hollandais(e)",
			answer: "Nederlands(e)",
			direction: "fr->nl",
			options: ["Nederlands(e)", "Frans", "hier", "dus"],
		},
		{
			id: "vocA-21",
			type: "vocab",
			prompt: "et",
			answer: "en",
			direction: "fr->nl",
		},
		{
			id: "vocA-22",
			type: "vocab",
			prompt: "en",
			answer: "et",
			direction: "nl->fr",
			hint: "kort woordje: et (spreek uit als ‘e’)",
		},
		{
			id: "vocA-23",
			type: "vocab",
			prompt: "oui",
			answer: "ja",
			direction: "fr->nl",
		},
		{
			id: "vocA-24",
			type: "vocab",
			prompt: "ja",
			answer: "oui",
			direction: "nl->fr",
		},
		{
			id: "vocA-25",
			type: "vocab",
			prompt: "non",
			answer: "nee",
			direction: "fr->nl",
		},
		{
			id: "vocA-26",
			type: "vocab",
			prompt: "nee",
			answer: "non",
			direction: "nl->fr",
		},
		{
			id: "vocA-27",
			type: "vocab",
			prompt: "ici",
			answer: "hier",
			direction: "fr->nl",
		},
		{
			id: "vocA-28",
			type: "vocab",
			prompt: "hier",
			answer: "ici",
			direction: "nl->fr",
			options: ["ici", "alors", "un peu", "et"],
		},
		{
			id: "vocA-29",
			type: "vocab",
			prompt: "alors",
			answer: "dus",
			direction: "fr->nl",
			hint: "gevolgtrekking: dus …",
		},
		{
			id: "vocA-30",
			type: "vocab",
			prompt: "dus",
			answer: "alors",
			direction: "nl->fr",
		},
		{
			id: "vocA-31",
			type: "vocab",
			prompt: "pardon",
			answer: "sorry",
			direction: "fr->nl",
			options: ["sorry", "dankjewel", "geen dank", "hallo"],
		},
		{
			id: "vocA-32",
			type: "vocab",
			prompt: "sorry",
			answer: "pardon",
			direction: "nl->fr",
		},
		{
			id: "vocA-33",
			type: "vocab",
			prompt: "merci",
			answer: "dankjewel",
			direction: "fr->nl",
		},
		{
			id: "vocA-34",
			type: "vocab",
			prompt: "dankjewel",
			answer: "merci",
			direction: "nl->fr",
			options: ["merci", "de rien", "pardon", "voilà"],
		},
		{
			id: "vocA-35",
			type: "vocab",
			prompt: "geen dank",
			answer: "de rien",
			direction: "nl->fr",
		},
		{
			id: "vocA-36",
			type: "vocab",
			prompt: "de rien",
			answer: "geen dank",
			direction: "fr->nl",
			options: ["geen dank", "dankjewel", "sorry", "tot ziens"],
		},
		{
			id: "vocA-37",
			type: "vocab",
			prompt: "bonjour",
			answer: "hallo",
			direction: "fr->nl",
			hint: "letterlijk: ‘goede dag’",
		},
		{
			id: "vocA-38",
			type: "vocab",
			prompt: "hallo",
			answer: "bonjour",
			direction: "nl->fr",
			options: ["bonjour", "au revoir", "merci", "oui"],
		},
		{
			id: "vocA-39",
			type: "vocab",
			prompt: "tot ziens",
			answer: "au revoir",
			direction: "nl->fr",
		},
		{
			id: "vocA-40",
			type: "vocab",
			prompt: "au revoir",
			answer: "tot ziens",
			direction: "fr->nl",
			options: ["tot ziens", "hallo", "geen dank", "dankjewel"],
		},
		// --- A - Zinnen ---
		{
			id: "vocA-41",
			type: "vocab",
			prompt: "Comment tu t'appelles?",
			answer: "Hoe heet jij?",
			direction: "fr->nl",
			hint: "vraag naar iemands naam",
		},
		{
			id: "vocA-42",
			type: "vocab",
			prompt: "Hoe heet jij?",
			answer: "Comment tu t'appelles?",
			direction: "nl->fr",
			options: [
				"Comment tu t'appelles?",
				"Je m'appelle Max.",
				"Tu habites où?",
				"J'habite à Breda, aux Pays-Bas.",
			],
		},
		{
			id: "vocA-43",
			type: "vocab",
			prompt: "Je m'appelle Max.",
			answer: "Ik heet Max.",
			direction: "fr->nl",
		},
		{
			id: "vocA-44",
			type: "vocab",
			prompt: "Ik heet Max.",
			answer: "Je m'appelle Max.",
			direction: "nl->fr",
			options: [
				"Je m'appelle Max.",
				"Comment tu t'appelles?",
				"Tu habites où?",
				"J'habite à Breda, aux Pays-Bas.",
			],
		},
		{
			id: "vocA-45",
			type: "vocab",
			prompt: "Tu habites où?",
			answer: "Waar woon jij?",
			direction: "fr->nl",
			hint: "où = waar (niet ou = of!)",
		},
		{
			id: "vocA-46",
			type: "vocab",
			prompt: "Waar woon jij?",
			answer: "Tu habites où?",
			direction: "nl->fr",
			options: [
				"Tu habites où?",
				"Comment tu t'appelles?",
				"Je m'appelle Max.",
				"J'habite à Breda, aux Pays-Bas.",
			],
		},
		{
			id: "vocA-47",
			type: "vocab",
			prompt: "J'habite à Breda, aux Pays-Bas.",
			answer: "Ik woon in Breda, in Nederland.",
			direction: "fr->nl",
			hint: "aux Pays-Bas = in Nederland",
		},
		{
			id: "vocA-48",
			type: "vocab",
			prompt: "Ik woon in Breda, in Nederland.",
			answer: "J'habite à Breda, aux Pays-Bas.",
			direction: "nl->fr",
			options: [
				"J'habite à Breda, aux Pays-Bas.",
				"Comment tu t'appelles?",
				"Je m'appelle Max.",
				"Tu habites où?",
			],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
