import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-vocabulaire-c",
	title: "Français – Apprendre vocabulaire C : se présenter",
	description:
		"Woordenschat C: jezelf voorstellen. Oefen woordenschat Nederlands ↔ Frans.",
	language: "french",
	exercises: [
		{
			id: "vocC-1",
			type: "vocab",
			prompt: "Bonjour, ça va?",
			answer: "Hallo, hoi, hoe gaat het?",
			alternatives: [
				"Hallo, hoi, hoe gaat het",
				"Hallo, hoe gaat het?",
				"Hoi, hoe gaat het?",
				"Hallo",
				"Hoi",
			],
			direction: "fr->nl",
			hint: "ça va = hoe gaat het (let op ç)",
		},
		{
			id: "vocC-2",
			type: "vocab",
			prompt: "Hallo / Hoi, hoe gaat het?",
			answer: "Bonjour, ça va?",
			direction: "nl->fr",
			options: [
				"Bonjour, ça va?",
				"Ça va bien, et toi?",
				"C'est quoi, Breda?",
				"C'est une ville.",
			],
		},
		{
			id: "vocC-3",
			type: "vocab",
			prompt: "Ça va bien, et toi?",
			answer: "Het gaat goed, en met jou?",
			alternatives: ["Het gaat goed, en met jou", "Het gaat goed"],
			direction: "fr->nl",
			hint: "et toi = en met jou",
		},
		{
			id: "vocC-4",
			type: "vocab",
			prompt: "Het gaat goed, en met jou?",
			answer: "Ça va bien, et toi?",
			direction: "nl->fr",
			options: [
				"Ça va bien, et toi?",
				"Bonjour, ça va?",
				"Je m'appelle Max.",
				"Tu habites où?",
			],
		},
		{
			id: "vocC-5",
			type: "vocab",
			prompt: "Comment tu t'appelles?",
			answer: "Hoe heet jij?",
			alternatives: ["Hoe heet jij"],
			direction: "fr->nl",
			hint: "vraag naar iemands naam",
		},
		{
			id: "vocC-6",
			type: "vocab",
			prompt: "Hoe heet jij?",
			answer: "Comment tu t'appelles?",
			direction: "nl->fr",
			options: [
				"Comment tu t'appelles?",
				"Je m'appelle Max.",
				"Tu habites où?",
				"C'est quoi, Breda?",
			],
		},
		{
			id: "vocC-7",
			type: "vocab",
			prompt: "Je m'appelle Max.",
			answer: "Ik heet Max.",
			alternatives: ["Ik heet Max"],
			direction: "fr->nl",
		},
		{
			id: "vocC-8",
			type: "vocab",
			prompt: "Ik heet Max.",
			answer: "Je m'appelle Max.",
			direction: "nl->fr",
			options: [
				"Je m'appelle Max.",
				"Comment tu t'appelles?",
				"J'habite à Breda, aux Pays-Bas.",
				"C'est une ville.",
			],
		},
		{
			id: "vocC-9",
			type: "vocab",
			prompt: "Tu habites où?",
			answer: "Waar woon jij?",
			alternatives: ["Waar woon jij"],
			direction: "fr->nl",
			hint: "où = waar (niet ou = of!)",
		},
		{
			id: "vocC-10",
			type: "vocab",
			prompt: "Waar woon jij?",
			answer: "Tu habites où?",
			direction: "nl->fr",
			options: [
				"Tu habites où?",
				"J'habite à Breda, aux Pays-Bas.",
				"Comment tu t'appelles?",
				"Ça va bien, et toi?",
			],
		},
		{
			id: "vocC-11",
			type: "vocab",
			prompt: "J'habite à Breda, aux Pays-Bas.",
			answer: "Ik woon in Breda, in Nederland.",
			alternatives: ["Ik woon in Breda, in Nederland"],
			direction: "fr->nl",
			hint: "aux Pays-Bas = in Nederland",
		},
		{
			id: "vocC-12",
			type: "vocab",
			prompt: "Ik woon in Breda, in Nederland.",
			answer: "J'habite à Breda, aux Pays-Bas.",
			direction: "nl->fr",
			options: [
				"J'habite à Breda, aux Pays-Bas.",
				"Tu habites où?",
				"C'est quoi, Breda?",
				"Bonjour, ça va?",
			],
		},
		{
			id: "vocC-13",
			type: "vocab",
			prompt: "C'est quoi, Breda?",
			answer: "Wat is dat, Breda?",
			alternatives: ["Wat is dat, Breda"],
			direction: "fr->nl",
			hint: "quoi = wat",
		},
		{
			id: "vocC-14",
			type: "vocab",
			prompt: "Wat is dat, Breda?",
			answer: "C'est quoi, Breda?",
			direction: "nl->fr",
			options: [
				"C'est quoi, Breda?",
				"C'est une ville.",
				"Comment tu t'appelles?",
				"Ça va bien, et toi?",
			],
		},
		{
			id: "vocC-15",
			type: "vocab",
			prompt: "C'est une ville.",
			answer: "Dat is een stad.",
			alternatives: ["Dat is een stad"],
			direction: "fr->nl",
		},
		{
			id: "vocC-16",
			type: "vocab",
			prompt: "Dat is een stad.",
			answer: "C'est une ville.",
			direction: "nl->fr",
			options: [
				"C'est une ville.",
				"C'est quoi, Breda?",
				"Je m'appelle Max.",
				"Bonjour, ça va?",
			],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
