import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-vocabulaire-e",
	title: "Français – Apprendre vocabulaire E : la plage",
	description:
		"Woordenschat E: het strand (p. 53) en zinnen over jezelf voorstellen. Oefen woordenschat Nederlands ↔ Frans.",
	language: "french",
	exercises: [
		// --- E - Woorden ---
		{
			id: "vocE-1",
			type: "vocab",
			prompt: "la plage",
			answer: "het strand",
			direction: "fr->nl",
		},
		{
			id: "vocE-2",
			type: "vocab",
			prompt: "het strand",
			answer: "la plage",
			direction: "nl->fr",
			options: ["la plage", "la mer", "la piscine", "l'hôtel"],
		},
		{
			id: "vocE-3",
			type: "vocab",
			prompt: "de zee",
			answer: "la mer",
			direction: "nl->fr",
		},
		{
			id: "vocE-4",
			type: "vocab",
			prompt: "la mer",
			answer: "de zee",
			direction: "fr->nl",
			options: ["de zee", "het strand", "het zwembad", "de boodschap"],
		},
		{
			id: "vocE-5",
			type: "vocab",
			prompt: "le problème",
			answer: "het probleem",
			direction: "fr->nl",
			hint: "let op è",
		},
		{
			id: "vocE-6",
			type: "vocab",
			prompt: "het probleem",
			answer: "le problème",
			direction: "nl->fr",
		},
		{
			id: "vocE-7",
			type: "vocab",
			prompt: "de boodschap",
			answer: "le message",
			direction: "nl->fr",
		},
		{
			id: "vocE-8",
			type: "vocab",
			prompt: "le message",
			answer: "de boodschap",
			direction: "fr->nl",
			options: ["de boodschap", "het probleem", "het hotel", "de camping"],
		},
		{
			id: "vocE-9",
			type: "vocab",
			prompt: "pourquoi",
			answer: "waarom",
			direction: "fr->nl",
		},
		{
			id: "vocE-10",
			type: "vocab",
			prompt: "waarom",
			answer: "pourquoi",
			direction: "nl->fr",
			options: ["pourquoi", "beaucoup", "presque", "aussi"],
		},
		{
			id: "vocE-11",
			type: "vocab",
			prompt: "kijk (naar)",
			answer: "regarde",
			direction: "nl->fr",
			hint: "gebiedende wijs: regarde!",
		},
		{
			id: "vocE-12",
			type: "vocab",
			prompt: "regarde",
			answer: "kijk",
			direction: "fr->nl",
			options: ["kijk", "helpen", "waarom", "veel"],
		},
		{
			id: "vocE-13",
			type: "vocab",
			prompt: "aider",
			answer: "helpen",
			direction: "fr->nl",
			hint: "werkwoord (hele werkwoord)",
		},
		{
			id: "vocE-14",
			type: "vocab",
			prompt: "helpen",
			answer: "aider",
			direction: "nl->fr",
		},
		{
			id: "vocE-15",
			type: "vocab",
			prompt: "we zijn gek op",
			answer: "on adore",
			direction: "nl->fr",
		},
		{
			id: "vocE-16",
			type: "vocab",
			prompt: "on adore",
			answer: "we zijn gek op",
			direction: "fr->nl",
			options: [
				"we zijn gek op",
				"ik vind leuk, hou van",
				"ik heb liever",
				"altijd",
			],
		},
		{
			id: "vocE-17",
			type: "vocab",
			prompt: "très",
			answer: "erg",
			direction: "fr->nl",
			hint: "let op è",
		},
		{
			id: "vocE-18",
			type: "vocab",
			prompt: "erg",
			answer: "très",
			direction: "nl->fr",
		},
		{
			id: "vocE-19",
			type: "vocab",
			prompt: "te / te veel",
			answer: "trop",
			direction: "nl->fr",
		},
		{
			id: "vocE-20",
			type: "vocab",
			prompt: "trop",
			answer: "te, te veel",
			alternatives: ["te", "te veel"],
			direction: "fr->nl",
			options: ["te, te veel", "erg", "veel", "bijna"],
		},
		{
			id: "vocE-21",
			type: "vocab",
			prompt: "aujourd'hui",
			answer: "vandaag",
			direction: "fr->nl",
		},
		{
			id: "vocE-22",
			type: "vocab",
			prompt: "vandaag",
			answer: "aujourd'hui",
			direction: "nl->fr",
			hint: "let op de apostrof",
		},
		{
			id: "vocE-23",
			type: "vocab",
			prompt: "morgen",
			answer: "demain",
			direction: "nl->fr",
		},
		{
			id: "vocE-24",
			type: "vocab",
			prompt: "demain",
			answer: "morgen",
			direction: "fr->nl",
			options: ["morgen", "vandaag", "misschien", "altijd"],
		},
		{
			id: "vocE-25",
			type: "vocab",
			prompt: "peut-être",
			answer: "misschien",
			direction: "fr->nl",
			hint: "let op ê en het koppelteken",
		},
		{
			id: "vocE-26",
			type: "vocab",
			prompt: "misschien",
			answer: "peut-être",
			direction: "nl->fr",
		},
		{
			id: "vocE-27",
			type: "vocab",
			prompt: "oké",
			answer: "d'accord",
			direction: "nl->fr",
			hint: "let op de apostrof",
		},
		{
			id: "vocE-28",
			type: "vocab",
			prompt: "d'accord",
			answer: "oké",
			direction: "fr->nl",
			options: ["oké", "misschien", "bijna", "super"],
		},
		{
			id: "vocE-29",
			type: "vocab",
			prompt: "presque",
			answer: "bijna",
			direction: "fr->nl",
		},
		{
			id: "vocE-30",
			type: "vocab",
			prompt: "bijna",
			answer: "presque",
			direction: "nl->fr",
		},
		{
			id: "vocE-31",
			type: "vocab",
			prompt: "veel",
			answer: "beaucoup",
			direction: "nl->fr",
			hint: "beau + coup",
		},
		{
			id: "vocE-32",
			type: "vocab",
			prompt: "beaucoup",
			answer: "veel",
			direction: "fr->nl",
			options: ["veel", "erg", "te, te veel", "ook"],
		},
		{
			id: "vocE-33",
			type: "vocab",
			prompt: "quelque chose",
			answer: "iets",
			direction: "fr->nl",
		},
		{
			id: "vocE-34",
			type: "vocab",
			prompt: "iets",
			answer: "quelque chose",
			direction: "nl->fr",
			hint: "quelque + chose",
		},
		{
			id: "vocE-35",
			type: "vocab",
			prompt: "mooi",
			answer: "beau",
			direction: "nl->fr",
			options: ["beau", "bizarre", "super", "trop"],
		},
		{
			id: "vocE-36",
			type: "vocab",
			prompt: "beau",
			answer: "mooi",
			direction: "fr->nl",
			hint: "mannelijk enkelvoud",
		},
		{
			id: "vocE-37",
			type: "vocab",
			prompt: "super",
			answer: "super",
			direction: "fr->nl",
		},
		{
			id: "vocE-38",
			type: "vocab",
			prompt: "super (Frans)",
			answer: "super",
			direction: "nl->fr",
			options: ["super", "bizarre", "beau", "très"],
		},
		{
			id: "vocE-39",
			type: "vocab",
			prompt: "vreemd",
			answer: "bizarre",
			direction: "nl->fr",
			hint: "met -arre: bizarre",
		},
		{
			id: "vocE-40",
			type: "vocab",
			prompt: "bizarre",
			answer: "vreemd",
			direction: "fr->nl",
			options: ["vreemd", "mooi", "super", "groot"],
		},
		// --- E - Zinnen ---
		{
			id: "vocE-41",
			type: "vocab",
			prompt: "Et toi, tu as quel âge?",
			answer: "En jij, hoe oud ben jij?",
			direction: "fr->nl",
			hint: "vraag naar iemands leeftijd",
		},
		{
			id: "vocE-42",
			type: "vocab",
			prompt: "En jij, hoe oud ben jij?",
			answer: "Et toi, tu as quel âge?",
			direction: "nl->fr",
			options: [
				"Et toi, tu as quel âge?",
				"Moi, j'ai 12 ans.",
				"Quel est ton numéro de téléphone?",
				"Mon numéro, c'est le 06-12 20 09.",
			],
		},
		{
			id: "vocE-43",
			type: "vocab",
			prompt: "Moi, j'ai 12 ans.",
			answer: "Ik ben 12 jaar.",
			direction: "fr->nl",
		},
		{
			id: "vocE-44",
			type: "vocab",
			prompt: "Ik ben 12 jaar.",
			answer: "Moi, j'ai 12 ans.",
			direction: "nl->fr",
			options: [
				"Moi, j'ai 12 ans.",
				"Et toi, tu as quel âge?",
				"Quel est ton numéro de téléphone?",
				"Mon numéro, c'est le 06-12 20 09.",
			],
		},
		{
			id: "vocE-45",
			type: "vocab",
			prompt: "Quel est ton numéro de téléphone?",
			answer: "Wat is jouw telefoonnummer?",
			direction: "fr->nl",
		},
		{
			id: "vocE-46",
			type: "vocab",
			prompt: "Wat is jouw telefoonnummer?",
			answer: "Quel est ton numéro de téléphone?",
			direction: "nl->fr",
			options: [
				"Quel est ton numéro de téléphone?",
				"Et toi, tu as quel âge?",
				"Moi, j'ai 12 ans.",
				"Mon numéro, c'est le 06-12 20 09.",
			],
		},
		{
			id: "vocE-47",
			type: "vocab",
			prompt: "Mon numéro, c'est le 06-12 20 09.",
			answer: "Mijn telefoonnummer is 06-12 20 09.",
			direction: "fr->nl",
			hint: "cijfers mag je gewoon overnemen",
		},
		{
			id: "vocE-48",
			type: "vocab",
			prompt: "Mijn telefoonnummer is 06-12 20 09.",
			answer: "Mon numéro, c'est le 06-12 20 09.",
			direction: "nl->fr",
			options: [
				"Mon numéro, c'est le 06-12 20 09.",
				"Et toi, tu as quel âge?",
				"Moi, j'ai 12 ans.",
				"Quel est ton numéro de téléphone?",
			],
		},
		{
			id: "vocE-49",
			type: "vocab",
			prompt: "Au revoir!",
			answer: "Tot ziens!",
			alternatives: ["Tot ziens"],
			direction: "fr->nl",
		},
		{
			id: "vocE-50",
			type: "vocab",
			prompt: "Tot ziens!",
			answer: "Au revoir!",
			direction: "nl->fr",
			options: [
				"Au revoir!",
				"À plus!",
				"Et toi, tu as quel âge?",
				"Moi, j'ai 12 ans.",
				"Quel est ton numéro de téléphone?",
				"Mon numéro, c'est le 06-12 20 09.",
			],
		},
		{
			id: "vocE-51",
			type: "vocab",
			prompt: "À plus!",
			answer: "Tot later!",
			alternatives: ["Tot later"],
			direction: "fr->nl",
			hint: "letterlijk: ‘tot (straks) meer’",
		},
		{
			id: "vocE-52",
			type: "vocab",
			prompt: "Tot later!",
			answer: "À plus!",
			direction: "nl->fr",
			options: [
				"À plus!",
				"Au revoir!",
				"Et toi, tu as quel âge?",
				"Moi, j'ai 12 ans.",
				"Quel est ton numéro de téléphone?",
				"Mon numéro, c'est le 06-12 20 09.",
			],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
