import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-vocabulaire-f",
	title: "Français – Apprendre vocabulaire F : famille et maison",
	description:
		"Woordenschat F: familie, huis en zinnen over broers en zussen. Oefen woordenschat Nederlands ↔ Frans.",
	language: "french",
	exercises: [
		// --- F - Woorden ---
		{
			id: "vocF-1",
			type: "vocab",
			prompt: "la France",
			answer: "Frankrijk",
			direction: "fr->nl",
		},
		{
			id: "vocF-2",
			type: "vocab",
			prompt: "Frankrijk",
			answer: "la France",
			direction: "nl->fr",
			options: ["la France", "la ville", "la maison", "la photo"],
		},
		{
			id: "vocF-3",
			type: "vocab",
			prompt: "de stad",
			answer: "la ville",
			direction: "nl->fr",
		},
		{
			id: "vocF-4",
			type: "vocab",
			prompt: "la ville",
			answer: "de stad",
			direction: "fr->nl",
			options: ["de stad", "het huis", "Frankrijk", "de foto"],
		},
		{
			id: "vocF-5",
			type: "vocab",
			prompt: "la maison",
			answer: "het huis",
			direction: "fr->nl",
		},
		{
			id: "vocF-6",
			type: "vocab",
			prompt: "het huis",
			answer: "la maison",
			direction: "nl->fr",
			options: ["la maison", "la ville", "la France", "la mère"],
		},
		{
			id: "vocF-7",
			type: "vocab",
			prompt: "de vader",
			answer: "le père",
			direction: "nl->fr",
			hint: "let op è",
		},
		{
			id: "vocF-8",
			type: "vocab",
			prompt: "le père",
			answer: "de vader",
			direction: "fr->nl",
			options: ["de vader", "de moeder", "de broer", "de sport"],
		},
		{
			id: "vocF-9",
			type: "vocab",
			prompt: "la mère",
			answer: "de moeder",
			direction: "fr->nl",
			hint: "let op è",
		},
		{
			id: "vocF-10",
			type: "vocab",
			prompt: "de moeder",
			answer: "la mère",
			direction: "nl->fr",
			options: ["la mère", "le père", "la maison", "la crêpe"],
		},
		{
			id: "vocF-11",
			type: "vocab",
			prompt: "de grootouders (mannelijk meervoud)",
			answer: "les grands-parents",
			direction: "nl->fr",
		},
		{
			id: "vocF-12",
			type: "vocab",
			prompt: "les grands-parents",
			answer: "de grootouders",
			direction: "fr->nl",
			options: ["de grootouders", "de ouders", "de vader", "de moeder"],
		},
		{
			id: "vocF-13",
			type: "vocab",
			prompt: "la photo",
			answer: "de foto",
			direction: "fr->nl",
		},
		{
			id: "vocF-14",
			type: "vocab",
			prompt: "de foto",
			answer: "la photo",
			direction: "nl->fr",
			options: ["la photo", "la France", "la ville", "la maison"],
		},
		{
			id: "vocF-15",
			type: "vocab",
			prompt: "aller",
			answer: "gaan",
			direction: "fr->nl",
			hint: "werkwoord (hele werkwoord)",
		},
		{
			id: "vocF-16",
			type: "vocab",
			prompt: "gaan",
			answer: "aller",
			direction: "nl->fr",
			options: ["aller", "voir", "visiter", "on fait"],
		},
		{
			id: "vocF-17",
			type: "vocab",
			prompt: "bezoeken",
			answer: "visiter",
			direction: "nl->fr",
			hint: "werkwoord (hele werkwoord)",
		},
		{
			id: "vocF-18",
			type: "vocab",
			prompt: "visiter",
			answer: "bezoeken",
			direction: "fr->nl",
			options: ["bezoeken", "gaan", "zien", "we eten"],
		},
		{
			id: "vocF-19",
			type: "vocab",
			prompt: "dangereux",
			answer: "gevaarlijk",
			direction: "fr->nl",
		},
		{
			id: "vocF-20",
			type: "vocab",
			prompt: "gevaarlijk",
			answer: "dangereux",
			direction: "nl->fr",
			options: ["dangereux", "sportif", "autre", "beau"],
		},
		{
			id: "vocF-21",
			type: "vocab",
			prompt: "sportief",
			answer: "sportif",
			direction: "nl->fr",
		},
		{
			id: "vocF-22",
			type: "vocab",
			prompt: "sportif",
			answer: "sportief",
			direction: "fr->nl",
			options: ["sportief", "gevaarlijk", "ander", "mooi"],
		},
		{
			id: "vocF-23",
			type: "vocab",
			prompt: "elle déteste",
			answer: "ze heeft een hekel aan",
			direction: "fr->nl",
			hint: "détester = een hekel hebben aan",
		},
		{
			id: "vocF-24",
			type: "vocab",
			prompt: "ze heeft een hekel aan",
			answer: "elle déteste",
			direction: "nl->fr",
		},
		{
			id: "vocF-25",
			type: "vocab",
			prompt: "le sport",
			answer: "de sport",
			direction: "fr->nl",
		},
		{
			id: "vocF-26",
			type: "vocab",
			prompt: "de sport",
			answer: "le sport",
			direction: "nl->fr",
			options: ["le sport", "le fromage", "le père", "voir"],
		},
		{
			id: "vocF-27",
			type: "vocab",
			prompt: "on fait",
			answer: "we doen",
			direction: "fr->nl",
		},
		{
			id: "vocF-28",
			type: "vocab",
			prompt: "we doen",
			answer: "on fait",
			direction: "nl->fr",
			options: ["on fait", "on mange", "aller", "voir"],
		},
		{
			id: "vocF-29",
			type: "vocab",
			prompt: "voir",
			answer: "zien",
			direction: "fr->nl",
			hint: "werkwoord (hele werkwoord)",
		},
		{
			id: "vocF-30",
			type: "vocab",
			prompt: "zien",
			answer: "voir",
			direction: "nl->fr",
			options: ["voir", "aller", "visiter", "on fait"],
		},
		{
			id: "vocF-31",
			type: "vocab",
			prompt: "on mange",
			answer: "we eten",
			direction: "fr->nl",
		},
		{
			id: "vocF-32",
			type: "vocab",
			prompt: "we eten",
			answer: "on mange",
			direction: "nl->fr",
			options: ["on mange", "on fait", "visiter", "voir"],
		},
		{
			id: "vocF-33",
			type: "vocab",
			prompt: "le fromage",
			answer: "de kaas",
			direction: "fr->nl",
		},
		{
			id: "vocF-34",
			type: "vocab",
			prompt: "de kaas",
			answer: "le fromage",
			direction: "nl->fr",
			options: ["le fromage", "le sport", "la crêpe", "la photo"],
		},
		{
			id: "vocF-35",
			type: "vocab",
			prompt: "la crêpe",
			answer: "de pannenkoek",
			direction: "fr->nl",
			hint: "let op ê",
		},
		{
			id: "vocF-36",
			type: "vocab",
			prompt: "de pannenkoek",
			answer: "la crêpe",
			direction: "nl->fr",
			options: ["la crêpe", "la mère", "la photo", "la ville"],
		},
		{
			id: "vocF-37",
			type: "vocab",
			prompt: "autre",
			answer: "ander",
			direction: "fr->nl",
			hint: "mannelijk én vrouwelijk: autre",
		},
		{
			id: "vocF-38",
			type: "vocab",
			prompt: "ander(e)",
			answer: "autre",
			direction: "nl->fr",
			options: ["autre", "moi", "aller", "voir"],
		},
		{
			id: "vocF-39",
			type: "vocab",
			prompt: "moi",
			answer: "ik",
			direction: "fr->nl",
			hint: "losstaand voornaamwoord (bij nadruk), anders dan je",
		},
		{
			id: "vocF-40",
			type: "vocab",
			prompt: "ik (nadruk, losstaand)",
			answer: "moi",
			direction: "nl->fr",
			options: ["moi", "autre", "on", "elle"],
		},
		// --- F - Zinnen ---
		{
			id: "vocF-41",
			type: "vocab",
			prompt: "Tu as un frère?",
			answer: "Heb jij een broer?",
			direction: "fr->nl",
		},
		{
			id: "vocF-42",
			type: "vocab",
			prompt: "Heb jij een broer?",
			answer: "Tu as un frère?",
			direction: "nl->fr",
			options: [
				"Tu as un frère?",
				"Oui, j'ai un frère. Il s'appelle Romain.",
				"Il a quel âge?",
				"Il a 15 ans.",
			],
		},
		{
			id: "vocF-43",
			type: "vocab",
			prompt: "Oui, j'ai un frère. Il s'appelle Romain.",
			answer: "Ja, ik heb een broer. Hij heet Romain.",
			direction: "fr->nl",
		},
		{
			id: "vocF-44",
			type: "vocab",
			prompt: "Ja, ik heb een broer. Hij heet Romain.",
			answer: "Oui, j'ai un frère. Il s'appelle Romain.",
			direction: "nl->fr",
			options: [
				"Oui, j'ai un frère. Il s'appelle Romain.",
				"Tu as un frère?",
				"Il a quel âge?",
				"Il a 15 ans.",
			],
		},
		{
			id: "vocF-45",
			type: "vocab",
			prompt: "Il a quel âge?",
			answer: "Hoe oud is hij?",
			direction: "fr->nl",
			hint: "vergelijk: tu as quel âge? (hoe oud ben jij?)",
		},
		{
			id: "vocF-46",
			type: "vocab",
			prompt: "Hoe oud is hij?",
			answer: "Il a quel âge?",
			direction: "nl->fr",
			options: [
				"Il a quel âge?",
				"Tu as un frère?",
				"Oui, j'ai un frère. Il s'appelle Romain.",
				"Il a 15 ans.",
			],
		},
		{
			id: "vocF-47",
			type: "vocab",
			prompt: "Il a 15 ans.",
			answer: "Hij is 15 jaar.",
			direction: "fr->nl",
			hint: "letterlijk: ‘hij heeft 15 jaren’",
		},
		{
			id: "vocF-48",
			type: "vocab",
			prompt: "Hij is 15 jaar.",
			answer: "Il a 15 ans.",
			direction: "nl->fr",
			options: [
				"Il a 15 ans.",
				"Tu as un frère?",
				"Oui, j'ai un frère. Il s'appelle Romain.",
				"Il a quel âge?",
			],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
