import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-vocabulaire-g",
	title: "Français – Apprendre vocabulaire G : parler de ta famille",
	description:
		"Woordenschat G: praten over je familie. Oefen woordenschat Nederlands ↔ Frans.",
	language: "french",
	exercises: [
		{
			id: "vocG-1",
			type: "vocab",
			prompt: "Tu as un frère?",
			answer: "Heb je een broer?",
			alternatives: ["Heb je een broer"],
			direction: "fr->nl",
		},
		{
			id: "vocG-2",
			type: "vocab",
			prompt: "Heb je een broer?",
			answer: "Tu as un frère?",
			direction: "nl->fr",
			options: [
				"Tu as un frère?",
				"Oui, j'ai un frère. Il s'appelle Romain.",
				"Il a quel âge?",
				"Et toi, tu as quel âge?",
			],
		},
		{
			id: "vocG-3",
			type: "vocab",
			prompt: "Oui, j'ai un frère. Il s'appelle Romain.",
			answer: "Ja, ik heb een broer. Hij heet Romain.",
			alternatives: ["Ja, ik heb een broer. Hij heet Romain"],
			direction: "fr->nl",
		},
		{
			id: "vocG-4",
			type: "vocab",
			prompt: "Ja, ik heb een broer. Hij heet Romain.",
			answer: "Oui, j'ai un frère. Il s'appelle Romain.",
			direction: "nl->fr",
			options: [
				"Oui, j'ai un frère. Il s'appelle Romain.",
				"Tu as un frère?",
				"Il a 15 ans.",
				"Moi, j'ai 12 ans.",
			],
		},
		{
			id: "vocG-5",
			type: "vocab",
			prompt: "Il a quel âge?",
			answer: "Hoe oud is hij?",
			alternatives: ["Hoe oud is hij"],
			direction: "fr->nl",
		},
		{
			id: "vocG-6",
			type: "vocab",
			prompt: "Hoe oud is hij?",
			answer: "Il a quel âge?",
			direction: "nl->fr",
			options: [
				"Il a quel âge?",
				"Il a 15 ans.",
				"Et toi, tu as quel âge?",
				"Tu as un frère?",
			],
		},
		{
			id: "vocG-7",
			type: "vocab",
			prompt: "Il a 15 ans.",
			answer: "Hij is 15 jaar.",
			alternatives: ["Hij is 15 jaar"],
			direction: "fr->nl",
			hint: "letterlijk: ‘hij heeft 15 jaren’",
		},
		{
			id: "vocG-8",
			type: "vocab",
			prompt: "Hij is 15 jaar.",
			answer: "Il a 15 ans.",
			direction: "nl->fr",
			options: [
				"Il a 15 ans.",
				"Il a quel âge?",
				"Moi, j'ai 12 ans.",
				"Oui, j'ai un frère. Il s'appelle Romain.",
			],
		},
		{
			id: "vocG-9",
			type: "vocab",
			prompt: "Et toi, tu as quel âge?",
			answer: "En jij, hoe oud ben jij?",
			alternatives: ["En jij, hoe oud ben jij"],
			direction: "fr->nl",
			hint: "vraag naar iemands leeftijd",
		},
		{
			id: "vocG-10",
			type: "vocab",
			prompt: "En jij, hoe oud ben jij?",
			answer: "Et toi, tu as quel âge?",
			direction: "nl->fr",
			options: [
				"Et toi, tu as quel âge?",
				"Il a quel âge?",
				"Moi, j'ai 12 ans.",
				"Quel est ton numéro de téléphone?",
			],
		},
		{
			id: "vocG-11",
			type: "vocab",
			prompt: "Moi, j'ai 12 ans.",
			answer: "Ik ben 12 jaar.",
			alternatives: ["Ik ben 12 jaar"],
			direction: "fr->nl",
		},
		{
			id: "vocG-12",
			type: "vocab",
			prompt: "Ik ben 12 jaar.",
			answer: "Moi, j'ai 12 ans.",
			direction: "nl->fr",
			options: [
				"Moi, j'ai 12 ans.",
				"Il a 15 ans.",
				"Et toi, tu as quel âge?",
				"Mon numéro, c'est le 06-12 20 09.",
			],
		},
		{
			id: "vocG-13",
			type: "vocab",
			prompt: "Quel est ton numéro de téléphone?",
			answer: "Wat is jouw telefoonnummer?",
			alternatives: ["Wat is jouw telefoonnummer"],
			direction: "fr->nl",
		},
		{
			id: "vocG-14",
			type: "vocab",
			prompt: "Wat is jouw telefoonnummer?",
			answer: "Quel est ton numéro de téléphone?",
			direction: "nl->fr",
			options: [
				"Quel est ton numéro de téléphone?",
				"Mon numéro, c'est le 06-12 20 09.",
				"Tu as un frère?",
				"Il a quel âge?",
			],
		},
		{
			id: "vocG-15",
			type: "vocab",
			prompt: "Mon numéro, c'est le 06-12 20 09.",
			answer: "Mijn nummer is 06-12 20 09.",
			alternatives: ["Mijn nummer is 06-12 20 09"],
			direction: "fr->nl",
			hint: "cijfers mag je gewoon overnemen",
		},
		{
			id: "vocG-16",
			type: "vocab",
			prompt: "Mijn nummer is 06-12 20 09.",
			answer: "Mon numéro, c'est le 06-12 20 09.",
			direction: "nl->fr",
			options: [
				"Mon numéro, c'est le 06-12 20 09.",
				"Quel est ton numéro de téléphone?",
				"Moi, j'ai 12 ans.",
				"Oui, j'ai un frère. Il s'appelle Romain.",
			],
		},
		{
			id: "vocG-17",
			type: "vocab",
			prompt: "Au revoir.",
			answer: "Tot ziens.",
			alternatives: ["Tot ziens"],
			direction: "fr->nl",
		},
		{
			id: "vocG-18",
			type: "vocab",
			prompt: "Tot ziens.",
			answer: "Au revoir.",
			direction: "nl->fr",
			options: ["Au revoir.", "À plus.", "Tu as un frère?", "Il a 15 ans."],
		},
		{
			id: "vocG-19",
			type: "vocab",
			prompt: "À plus.",
			answer: "Tot later.",
			alternatives: ["Tot later"],
			direction: "fr->nl",
			hint: "letterlijk: ‘tot (straks) meer’",
		},
		{
			id: "vocG-20",
			type: "vocab",
			prompt: "Tot later.",
			answer: "À plus.",
			direction: "nl->fr",
			options: ["À plus.", "Au revoir.", "Et toi, tu as quel âge?", "Moi, j'ai 12 ans."],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
