import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "french-vocabulaire-b",
	title: "Français – Apprendre vocabulaire B : hôtel et famille",
	description:
		"Woordenschat B: hotel en familie. Oefen woordenschat Nederlands ↔ Frans.",
	language: "french",
	exercises: [
		{
			id: "vocB-1",
			type: "vocab",
			prompt: "l'hôtel",
			answer: "het hotel",
			direction: "fr->nl",
			hint: "mannelijk (m)",
		},
		{
			id: "vocB-2",
			type: "vocab",
			prompt: "het hotel",
			answer: "l'hôtel",
			direction: "nl->fr",
			options: ["l'hôtel", "la piscine", "le garçon", "la sœur"],
		},
		{
			id: "vocB-3",
			type: "vocab",
			prompt: "het zwembad",
			answer: "la piscine",
			direction: "nl->fr",
		},
		{
			id: "vocB-4",
			type: "vocab",
			prompt: "la piscine",
			answer: "het zwembad",
			direction: "fr->nl",
			options: ["het zwembad", "het hotel", "de zus", "de broer"],
		},
		{
			id: "vocB-5",
			type: "vocab",
			prompt: "la fille",
			answer: "het meisje",
			direction: "fr->nl",
		},
		{
			id: "vocB-6",
			type: "vocab",
			prompt: "het meisje",
			answer: "la fille",
			direction: "nl->fr",
			options: ["la fille", "le garçon", "la sœur", "la famille"],
		},
		{
			id: "vocB-7",
			type: "vocab",
			prompt: "de jongen",
			answer: "le garçon",
			direction: "nl->fr",
			hint: "let op de ç (cédille) – gebruik de accent-balk",
		},
		{
			id: "vocB-8",
			type: "vocab",
			prompt: "le garçon",
			answer: "de jongen",
			direction: "fr->nl",
			options: ["de jongen", "het meisje", "de broer", "de familie"],
		},
		{
			id: "vocB-9",
			type: "vocab",
			prompt: "génial / géniale",
			answer: "geweldig",
			direction: "fr->nl",
		},
		{
			id: "vocB-10",
			type: "vocab",
			prompt: "geweldig",
			answer: "génial",
			direction: "nl->fr",
			options: ["génial", "petit", "grand", "avec"],
		},
		{
			id: "vocB-11",
			type: "vocab",
			prompt: "alstublieft (bij iets vragen)",
			answer: "s'il vous plaît",
			direction: "nl->fr",
			hint: "tegenover voilà (bij iets géven)",
		},
		{
			id: "vocB-12",
			type: "vocab",
			prompt: "s'il vous plaît",
			answer: "alstublieft (iets vragen)",
			direction: "fr->nl",
			options: [
				"alstublieft (iets vragen)",
				"alsjeblieft (iets geven)",
				"geen dank",
				"dankjewel",
			],
		},
		{
			id: "vocB-13",
			type: "vocab",
			prompt: "avec",
			answer: "met",
			direction: "fr->nl",
		},
		{
			id: "vocB-14",
			type: "vocab",
			prompt: "met",
			answer: "avec",
			direction: "nl->fr",
		},
		{
			id: "vocB-15",
			type: "vocab",
			prompt: "ook",
			answer: "aussi",
			direction: "nl->fr",
		},
		{
			id: "vocB-16",
			type: "vocab",
			prompt: "aussi",
			answer: "ook",
			direction: "fr->nl",
			options: ["ook", "altijd", "met", "in"],
		},
		{
			id: "vocB-17",
			type: "vocab",
			prompt: "toujours",
			answer: "altijd",
			direction: "fr->nl",
		},
		{
			id: "vocB-18",
			type: "vocab",
			prompt: "altijd",
			answer: "toujours",
			direction: "nl->fr",
		},
		{
			id: "vocB-19",
			type: "vocab",
			prompt: "dans",
			answer: "in",
			direction: "fr->nl",
		},
		{
			id: "vocB-20",
			type: "vocab",
			prompt: "in",
			answer: "dans",
			direction: "nl->fr",
			options: ["dans", "avec", "aussi", "ici"],
		},
		{
			id: "vocB-21",
			type: "vocab",
			prompt: "la famille",
			answer: "de familie",
			direction: "fr->nl",
		},
		{
			id: "vocB-22",
			type: "vocab",
			prompt: "de familie",
			answer: "la famille",
			direction: "nl->fr",
			options: ["la famille", "la fille", "la sœur", "les parents"],
		},
		{
			id: "vocB-23",
			type: "vocab",
			prompt: "de ouders (mannelijk meervoud)",
			answer: "les parents",
			direction: "nl->fr",
		},
		{
			id: "vocB-24",
			type: "vocab",
			prompt: "les parents",
			answer: "de ouders",
			direction: "fr->nl",
			options: ["de ouders", "de familie", "de zus", "de broer"],
		},
		{
			id: "vocB-25",
			type: "vocab",
			prompt: "il y a",
			answer: "er is, er zijn",
			alternatives: ["er is", "er zijn"],
			direction: "fr->nl",
		},
		{
			id: "vocB-26",
			type: "vocab",
			prompt: "er is / er zijn",
			answer: "il y a",
			direction: "nl->fr",
			hint: "onveranderlijk: il y a",
		},
		{
			id: "vocB-27",
			type: "vocab",
			prompt: "de zus",
			answer: "la sœur",
			direction: "nl->fr",
			hint: "let op œ – gebruik de accent-balk",
		},
		{
			id: "vocB-28",
			type: "vocab",
			prompt: "la sœur",
			answer: "de zus",
			direction: "fr->nl",
			options: ["de zus", "de broer", "het meisje", "de familie"],
		},
		{
			id: "vocB-29",
			type: "vocab",
			prompt: "le frère",
			answer: "de broer",
			direction: "fr->nl",
			hint: "let op è (accent grave)",
		},
		{
			id: "vocB-30",
			type: "vocab",
			prompt: "de broer",
			answer: "le frère",
			direction: "nl->fr",
			options: ["le frère", "la sœur", "le garçon", "la famille"],
		},
		{
			id: "vocB-31",
			type: "vocab",
			prompt: "ik vind leuk / ik hou van",
			answer: "j'aime",
			direction: "nl->fr",
		},
		{
			id: "vocB-32",
			type: "vocab",
			prompt: "j'aime",
			answer: "ik vind leuk, hou van",
			alternatives: ["ik vind leuk", "hou van"],
			direction: "fr->nl",
			options: [
				"ik vind leuk, hou van",
				"ik heb liever",
				"we zijn gek op",
				"ik zoek",
			],
		},
		{
			id: "vocB-33",
			type: "vocab",
			prompt: "je préfère",
			answer: "ik heb liever",
			direction: "fr->nl",
			hint: "let op è en é",
		},
		{
			id: "vocB-34",
			type: "vocab",
			prompt: "ik heb liever",
			answer: "je préfère",
			direction: "nl->fr",
		},
		{
			id: "vocB-35",
			type: "vocab",
			prompt: "dat is / het is",
			answer: "c'est",
			direction: "nl->fr",
		},
		{
			id: "vocB-36",
			type: "vocab",
			prompt: "c'est",
			answer: "dat is, het is",
			alternatives: ["dat is", "het is"],
			direction: "fr->nl",
			options: ["dat is, het is", "hij is", "er is, er zijn", "ik ben"],
		},
		{
			id: "vocB-37",
			type: "vocab",
			prompt: "petit / petite",
			answer: "klein",
			direction: "fr->nl",
		},
		{
			id: "vocB-38",
			type: "vocab",
			prompt: "klein",
			answer: "petit",
			direction: "nl->fr",
			options: ["petit", "grand", "avec", "dans"],
		},
		{
			id: "vocB-39",
			type: "vocab",
			prompt: "groot",
			answer: "grand",
			alternatives: ["grande"],
			direction: "nl->fr",
			hint: "mannelijk: grand, vrouwelijk: grande",
		},
		{
			id: "vocB-40",
			type: "vocab",
			prompt: "grand / grande",
			answer: "groot",
			direction: "fr->nl",
			options: ["groot", "klein", "met", "ook"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
