import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "english-1",
	title: "English – Beginner 1 : Hello!",
	description:
		"Everyday greetings, basic vocabulary and the verbs to be & to have.",
	language: "english",
	exercises: [
		{
			id: "en1-1",
			type: "vocab",
			prompt: "hallo",
			answer: "hello",
			direction: "nl->en",
		},
		{
			id: "en1-2",
			type: "vocab",
			prompt: "hello",
			answer: "hallo",
			direction: "en->nl",
			options: ["hallo", "tot ziens", "dank je", "ja"],
		},
		{
			id: "en1-3",
			type: "vocab",
			prompt: "dank je",
			answer: "thank you",
			alternatives: ["thanks"],
			direction: "nl->en",
		},
		{
			id: "en1-4",
			type: "vocab",
			prompt: "thank you",
			answer: "dank je",
			direction: "en->nl",
			options: ["dank je", "alstublieft", "hallo", "nee"],
		},
		{
			id: "en1-5",
			type: "vocab",
			prompt: "ja",
			answer: "yes",
			direction: "nl->en",
			options: ["yes", "no", "please", "hello"],
		},
		{
			id: "en1-6",
			type: "vocab",
			prompt: "nee",
			answer: "no",
			direction: "nl->en",
		},
		{
			id: "en1-7",
			type: "vocab",
			prompt: "het huis",
			answer: "the house",
			alternatives: ["house"],
			direction: "nl->en",
			hint: "verg uit lidwoord: the",
		},
		{
			id: "en1-8",
			type: "vocab",
			prompt: "the house",
			answer: "het huis",
			direction: "en->nl",
			options: ["het huis", "de tafel", "de stoel", "het water"],
		},
		{
			id: "en1-9",
			type: "vocab",
			prompt: "water",
			answer: "water",
			direction: "nl->en",
		},
		{
			id: "en1-10",
			type: "vocab",
			prompt: "ster",
			answer: "star",
			direction: "nl->en",
		},
		{
			id: "en1-11",
			type: "declension",
			prompt: "to be – ik ben (1st person singular, present)",
			lemma: "to be – zijn",
			form: "I ...",
			answer: "I am",
			alternatives: ["am"],
			hint: "I am, you are, he/she is",
			options: ["I am", "I have", "I do", "I will"],
		},
		{
			id: "en1-12",
			type: "declension",
			prompt: "to have – wij hebben (1st person plural)",
			lemma: "to have – hebben",
			form: "we ...",
			answer: "we have",
			alternatives: ["have"],
			hint: "I have, you have, he has, we have, you have, they have",
		},
		{
			id: "en1-13",
			type: "vocab",
			prompt: "alstublieft",
			answer: "please",
			direction: "nl->en",
		},
		{
			id: "en1-14",
			type: "vocab",
			prompt: "goodbye",
			answer: "tot ziens",
			direction: "en->nl",
			options: ["tot ziens", "hallo", "welterusten", "dank je"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);
