import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "english-1",
	title: "English – Unit I",
	description:
		"Woordenschat Unit I: landen, klaslokaal, instrumenten en activiteiten. Oefen Nederlands ↔ Engels met uitspraak (IPA).",
	language: "english",
	exercises: [
		{
			id: "en1-1",
			type: "vocab",
			prompt: "Argentinië",
			answer: "Argentina",
			direction: "nl->en",
			hint: "n /ˌɑːdʒənˈtiːnə/",
		},
		{
			id: "en1-2",
			type: "vocab",
			prompt: "Australia",
			answer: "Australië",
			direction: "en->nl",
			hint: "n /ɒˈstreɪliə/",
			options: ["Oekraïne", "Argentinië", "Australië", "China"],
		},
		{
			id: "en1-3",
			type: "vocab",
			prompt: "prullenbak",
			answer: "bin",
			direction: "nl->en",
			hint: "n /bɪn/",
		},
		{
			id: "en1-4",
			type: "vocab",
			prompt: "blackboard",
			answer: "schoolbord",
			direction: "en->nl",
			hint: "n /ˈblækbɔːd/",
			options: ["rekenmachine", "kast", "etui", "schoolbord"],
		},
		{
			id: "en1-5",
			type: "vocab",
			prompt: "Brazilië",
			answer: "Brazil",
			direction: "nl->en",
			hint: "n /brəˈzɪl/",
		},
		{
			id: "en1-6",
			type: "vocab",
			prompt: "calculator",
			answer: "rekenmachine",
			direction: "en->nl",
			hint: "n /ˈkælkjuleɪtə(r)/",
			options: ["plank", "prullenbak", "rekenmachine", "schoolbord"],
		},
		{
			id: "en1-7",
			type: "vocab",
			prompt: "Canada",
			answer: "Canada",
			direction: "nl->en",
			hint: "n /ˈkænədə/",
		},
		{
			id: "en1-8",
			type: "vocab",
			prompt: "chair",
			answer: "stoel",
			direction: "en->nl",
			hint: "n /tʃeə(r)/",
			options: ["etui", "gum", "stoel", "potlood"],
		},
		{
			id: "en1-9",
			type: "vocab",
			prompt: "China",
			answer: "China",
			direction: "nl->en",
			hint: "n /ˈtʃaɪnə/",
		},
		{
			id: "en1-10",
			type: "vocab",
			prompt: "clarinet",
			answer: "klarinet",
			direction: "en->nl",
			hint: "n /ˌklærəˈnet/",
			options: ["klarinet", "drums", "trompet", "piano"],
		},
		{
			id: "en1-11",
			type: "vocab",
			prompt: "computer",
			answer: "computer",
			direction: "nl->en",
			hint: "n /kəmˈpjuːtə(r)/",
		},
		{
			id: "en1-12",
			type: "vocab",
			prompt: "Croatia",
			answer: "Kroatië",
			direction: "en->nl",
			hint: "n /krəʊˈeɪʃə/",
			options: ["Griekenland", "Kroatië", "China", "India"],
		},
		{
			id: "en1-13",
			type: "vocab",
			prompt: "kast",
			answer: "cupboard",
			direction: "nl->en",
			hint: "n /ˈkʌbəd/",
		},
		{
			id: "en1-14",
			type: "vocab",
			prompt: "dance",
			answer: "dans",
			alternatives: ["dansen", "dans"],
			direction: "en->nl",
			hint: "v /dɑːns/",
			options: ["dans", "(basketbal) spelen", "fietsen", "schaatsen, skaten"],
		},
		{
			id: "en1-15",
			type: "vocab",
			prompt: "bureau",
			answer: "desk",
			direction: "nl->en",
			hint: "n /desk/",
		},
		{
			id: "en1-16",
			type: "vocab",
			prompt: "drums",
			answer: "drums",
			direction: "en->nl",
			hint: "n /drʌmz/",
			options: ["saxofoon", "keyboard", "klarinet", "drums"],
		},
		{
			id: "en1-17",
			type: "vocab",
			prompt: "Egypte",
			answer: "Egypt",
			direction: "nl->en",
			hint: "n /ˈiːdʒɪpt/",
		},
		{
			id: "en1-18",
			type: "vocab",
			prompt: "eraser",
			answer: "gum",
			direction: "en->nl",
			hint: "n /ɪˈreɪzə(r)/",
			options: ["pen", "gum", "potlood", "liniaal"],
		},
		{
			id: "en1-19",
			type: "vocab",
			prompt: "werkboek",
			answer: "exercise book",
			direction: "nl->en",
			hint: "n /ˈeksəsaɪz bʊk/",
		},
		{
			id: "en1-20",
			type: "vocab",
			prompt: "flute",
			answer: "fluit",
			direction: "en->nl",
			hint: "n /fluːt/",
			options: ["klarinet", "fluit", "saxofoon", "drums"],
		},
		{
			id: "en1-21",
			type: "vocab",
			prompt: "Frankrijk",
			answer: "France",
			direction: "nl->en",
			hint: "n /frɑːns/",
		},
		{
			id: "en1-22",
			type: "vocab",
			prompt: "Germany",
			answer: "Duitsland",
			direction: "en->nl",
			hint: "n /ˈdʒɜːməni/",
			options: ["Duitsland", "Japan", "Frankrijk", "Canada"],
		},
		{
			id: "en1-23",
			type: "vocab",
			prompt: "Griekenland",
			answer: "Greece",
			direction: "nl->en",
			hint: "n /ɡriːs/",
		},
		{
			id: "en1-24",
			type: "vocab",
			prompt: "guitar",
			answer: "gitaar",
			direction: "en->nl",
			hint: "n /ɡɪˈtɑː(r)/",
			options: ["gitaar", "trompet", "viool", "fluit"],
		},
		{
			id: "en1-25",
			type: "vocab",
			prompt: "Hongarije",
			answer: "Hungary",
			direction: "nl->en",
			hint: "n /ˈhʌŋɡəri/",
		},
		{
			id: "en1-26",
			type: "vocab",
			prompt: "India",
			answer: "India",
			direction: "en->nl",
			hint: "n /ˈɪndiə/",
			options: ["Brazilië", "Kroatië", "India", "Oekraïne"],
		},
		{
			id: "en1-27",
			type: "vocab",
			prompt: "digibord",
			answer: "interactive whiteboard",
			direction: "nl->en",
			hint: "n /ˌɪntərˈæktɪv ˈwaɪtbɔːd/",
		},
		{
			id: "en1-28",
			type: "vocab",
			prompt: "Italy",
			answer: "Italië",
			direction: "en->nl",
			hint: "n /ˈɪtəli/",
			options: ["Italië", "het Verenigd Koninkrijk", "Duitsland", "Japan"],
		},
		{
			id: "en1-29",
			type: "vocab",
			prompt: "Japan",
			answer: "Japan",
			direction: "nl->en",
			hint: "n /dʒəˈpæn/",
		},
		{
			id: "en1-30",
			type: "vocab",
			prompt: "keyboard",
			answer: "keyboard",
			direction: "en->nl",
			hint: "n /ˈkiːbɔːd/",
			options: ["keyboard", "viool", "klarinet", "drums"],
		},
		{
			id: "en1-31",
			type: "vocab",
			prompt: "Mexico",
			answer: "Mexico",
			direction: "nl->en",
			hint: "n /ˈmeksɪkəʊ/",
		},
		{
			id: "en1-32",
			type: "vocab",
			prompt: "pen",
			answer: "pen",
			direction: "en->nl",
			hint: "n /pen/",
			options: ["digibord", "rekenmachine", "pen", "stoel"],
		},
		{
			id: "en1-33",
			type: "vocab",
			prompt: "potlood",
			answer: "pencil",
			direction: "nl->en",
			hint: "n /ˈpensl/",
		},
		{
			id: "en1-34",
			type: "vocab",
			prompt: "pencil case",
			answer: "etui",
			direction: "en->nl",
			hint: "n /ˈpensl keɪs/",
			options: ["schooltas", "puntenslijper", "etui", "pen"],
		},
		{
			id: "en1-35",
			type: "vocab",
			prompt: "puntenslijper",
			answer: "pencil sharpener",
			direction: "nl->en",
			hint: "n /ˈpensl ʃɑːpnə(r)/",
		},
		{
			id: "en1-36",
			type: "vocab",
			prompt: "piano",
			answer: "piano",
			direction: "en->nl",
			hint: "n /pɪˈænəʊ/",
			options: ["piano", "fluit", "saxofoon", "drums"],
		},
		{
			id: "en1-37",
			type: "vocab",
			prompt: "(basketbal) spelen",
			answer: "play (basketball)",
			alternatives: ["play", "play basketball"],
			direction: "nl->en",
			hint: "v /pleɪ/",
		},
		{
			id: "en1-38",
			type: "vocab",
			prompt: "Poland",
			answer: "Polen",
			direction: "en->nl",
			hint: "n /ˈpəʊlənd/",
			options: ["Italië", "India", "Polen", "de VS"],
		},
		{
			id: "en1-39",
			type: "vocab",
			prompt: "fietsen",
			answer: "ride (a bike)",
			alternatives: ["ride", "ride a bike"],
			direction: "nl->en",
			hint: "v /raɪd/",
		},
		{
			id: "en1-40",
			type: "vocab",
			prompt: "ruler",
			answer: "liniaal",
			direction: "en->nl",
			hint: "n /ˈruːlə(r)/",
			options: ["rekenmachine", "etui", "prullenbak", "liniaal"],
		},
		{
			id: "en1-41",
			type: "vocab",
			prompt: "Rusland",
			answer: "Russia",
			direction: "nl->en",
			hint: "n /ˈrʌʃə/",
		},
		{
			id: "en1-42",
			type: "vocab",
			prompt: "saxophone",
			answer: "saxofoon",
			direction: "en->nl",
			hint: "n /ˈsæksəfəʊn/",
			options: ["saxofoon", "keyboard", "trompet", "klarinet"],
		},
		{
			id: "en1-43",
			type: "vocab",
			prompt: "schooltas",
			answer: "schoolbag",
			direction: "nl->en",
			hint: "n /ˈskuːlbæɡ/",
		},
		{
			id: "en1-44",
			type: "vocab",
			prompt: "shelf",
			answer: "plank",
			direction: "en->nl",
			hint: "n /ʃelf/",
			options: ["werkboek", "puntenslijper", "schooltas", "plank"],
		},
		{
			id: "en1-45",
			type: "vocab",
			prompt: "zingen",
			answer: "sing",
			direction: "nl->en",
			hint: "v /sɪŋ/",
		},
		{
			id: "en1-46",
			type: "vocab",
			prompt: "skate",
			answer: "schaatsen, skaten",
			alternatives: ["schaatsen", "skaten"],
			direction: "en->nl",
			hint: "v /skeɪt/",
			options: ["skiën", "skateboard", "schaatsen, skaten", "praten, spreken"],
		},
		{
			id: "en1-47",
			type: "vocab",
			prompt: "skateboard",
			answer: "skateboard",
			direction: "nl->en",
			hint: "n /ˈskeɪtbɔːd/",
		},
		{
			id: "en1-48",
			type: "vocab",
			prompt: "ski",
			answer: "skiën",
			direction: "en->nl",
			hint: "v /skiː/",
			options: ["zingen", "praten, spreken", "(basketbal) spelen", "skiën"],
		},
		{
			id: "en1-49",
			type: "vocab",
			prompt: "Spanje",
			answer: "Spain",
			direction: "nl->en",
			hint: "n /speɪn/",
		},
		{
			id: "en1-50",
			type: "vocab",
			prompt: "speak",
			answer: "praten, spreken",
			alternatives: ["praten", "spreken"],
			direction: "en->nl",
			hint: "v /spiːk/",
			options: ["fietsen", "praten, spreken", "dans", "schaatsen, skaten"],
		},
		{
			id: "en1-51",
			type: "vocab",
			prompt: "zwemmen",
			answer: "swim",
			direction: "nl->en",
			hint: "v /swɪm/",
		},
		{
			id: "en1-52",
			type: "vocab",
			prompt: "the UK",
			answer: "het Verenigd Koninkrijk",
			direction: "en->nl",
			hint: "n /ðə ˌjuː ˈkeɪ/",
			options: ["Kroatië", "China", "India", "het Verenigd Koninkrijk"],
		},
		{
			id: "en1-53",
			type: "vocab",
			prompt: "de VS",
			answer: "the USA",
			alternatives: ["USA"],
			direction: "nl->en",
			hint: "n /ðə ˌjuː es ˈeɪ/",
		},
		{
			id: "en1-54",
			type: "vocab",
			prompt: "trumpet",
			answer: "trompet",
			direction: "en->nl",
			hint: "n /ˈtrʌmpɪt/",
			options: ["saxofoon", "trompet", "viool", "klarinet"],
		},
		{
			id: "en1-55",
			type: "vocab",
			prompt: "Turkije",
			answer: "Turkey",
			direction: "nl->en",
			hint: "n /ˈtɜːki/",
		},
		{
			id: "en1-56",
			type: "vocab",
			prompt: "Ukraine",
			answer: "Oekraïne",
			direction: "en->nl",
			hint: "n /juːˈkreɪn/",
			options: ["Frankrijk", "Australië", "het Verenigd Koninkrijk", "Oekraïne"],
		},
		{
			id: "en1-57",
			type: "vocab",
			prompt: "viool",
			answer: "violin",
			direction: "nl->en",
			hint: "n /ˌvaɪəˈlɪn/",
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);