import { type Chapter, chapterSchema } from "@/lib/schema";

const rawChapter = {
	id: "english-unit-1",
	title: "English – Unit 1",
	description:
		"Woordenschat Lesson 1: familie, karaktereigenschappen, uiterlijk en huishoudelijke taken. Oefen Nederlands ↔ Engels met uitspraak (IPA).",
	language: "english",
	exercises: [
		{
			id: "enL1-1",
			type: "vocab",
			prompt: "boos",
			answer: "angry",
			direction: "nl->en",
			hint: "adj /ˈæŋɡri/",
		},
		{
			id: "enL1-2",
			type: "vocab",
			prompt: "aunt",
			answer: "tante",
			direction: "en->nl",
			hint: "n /ɑːnt/",
			options: ["kleinkind", "tante", "kind", "kinderen"],
		},
		{
			id: "enL1-3",
			type: "vocab",
			prompt: "blauw",
			answer: "blue",
			direction: "nl->en",
			hint: "adj /bluː/",
		},
		{
			id: "enL1-4",
			type: "vocab",
			prompt: "brother",
			answer: "broer",
			direction: "en->nl",
			hint: "n /ˈbrʌðə(r)/",
			options: ["moeder", "broer", "kind", "oma"],
		},
		{
			id: "enL1-5",
			type: "vocab",
			prompt: "kind",
			answer: "child",
			direction: "nl->en",
			hint: "n /tʃaɪld/",
		},
		{
			id: "enL1-6",
			type: "vocab",
			prompt: "children",
			answer: "kinderen",
			direction: "en->nl",
			hint: "n /ˈtʃɪldrən/",
			options: ["dochter", "kinderen", "kleindochter", "papa"],
		},
		{
			id: "enL1-7",
			type: "vocab",
			prompt: "(het huis) schoonmaken",
			answer: "clean (the house)",
			alternatives: ["clean"],
			direction: "nl->en",
			hint: "v /kliːn/",
		},
		{
			id: "enL1-8",
			type: "vocab",
			prompt: "cook (dinner)",
			answer: "(eten) koken",
			direction: "en->nl",
			hint: "v /kʊk/",
			options: ["(de vaatwasser) inruimen", "strijken", "(het huis) schoonmaken", "(eten) koken"],
		},
		{
			id: "enL1-9",
			type: "vocab",
			prompt: "neef / nicht (het kind van je oom en tante)",
			answer: "cousin",
			direction: "nl->en",
			hint: "n /ˈkʌzn/",
		},
		{
			id: "enL1-10",
			type: "vocab",
			prompt: "creative",
			answer: "creatief",
			direction: "en->nl",
			hint: "adj /kriˈeɪtɪv/",
			options: ["blauw", "boos", "creatief", "geïnteresseerd"],
		},
		{
			id: "enL1-11",
			type: "vocab",
			prompt: "papa",
			answer: "dad",
			direction: "nl->en",
			hint: "n /dæd/",
		},
		{
			id: "enL1-12",
			type: "vocab",
			prompt: "daughter",
			answer: "dochter",
			direction: "en->nl",
			hint: "n /ˈdɔːtə(r)/",
			options: ["ouder", "neef / nicht (het kind van je oom en tante)", "dochter", "kind"],
		},
		{
			id: "enL1-13",
			type: "vocab",
			prompt: "strijken",
			answer: "do (the ironing)",
			alternatives: ["do"],
			direction: "nl->en",
			hint: "v /duː/",
		},
		{
			id: "enL1-14",
			type: "vocab",
			prompt: "father",
			answer: "vader",
			direction: "en->nl",
			hint: "n /ˈfɑːðə(r)/",
			options: ["kleinzoon", "vader", "grootmoeder / oma", "mama"],
		},
		{
			id: "enL1-15",
			type: "vocab",
			prompt: "vriendelijk",
			answer: "friendly",
			direction: "nl->en",
			hint: "adj /ˈfrendli/",
		},
		{
			id: "enL1-16",
			type: "vocab",
			prompt: "glasses",
			answer: "bril",
			direction: "en->nl",
			hint: "n /ˈɡlɑːsɪz/",
			options: ["bril", "vrouw, echtgenote", "snor", "patiënt"],
		},
		{
			id: "enL1-17",
			type: "vocab",
			prompt: "boodschappen doen",
			answer: "go (to the supermarket)",
			alternatives: ["go"],
			direction: "nl->en",
			hint: "v /ɡəʊ/",
		},
		{
			id: "enL1-18",
			type: "vocab",
			prompt: "grandad",
			answer: "opa",
			direction: "en->nl",
			hint: "n /ˈɡrændæd/",
			options: ["nicht (het kind van je broer of zus)", "dochter", "opa", "neef (het kind van je broer of zus)"],
		},
		{
			id: "enL1-19",
			type: "vocab",
			prompt: "kleinkind",
			answer: "grandchild",
			direction: "nl->en",
			hint: "n /ˈɡræntʃaɪld/",
		},
		{
			id: "enL1-20",
			type: "vocab",
			prompt: "grandchildren",
			answer: "kleinkinderen",
			direction: "en->nl",
			hint: "n /ˈɡræntʃɪldrən/",
			options: ["kleinkinderen", "oom", "nicht (het kind van je broer of zus)", "echtgenoot"],
		},
		{
			id: "enL1-21",
			type: "vocab",
			prompt: "kleindochter",
			answer: "granddaughter",
			direction: "nl->en",
			hint: "n /ˈɡrændɔːtə(r)/",
		},
		{
			id: "enL1-22",
			type: "vocab",
			prompt: "grandfather",
			answer: "grootvader / opa",
			alternatives: ["grootvader", "opa"],
			direction: "en->nl",
			hint: "n /ˈɡrænfɑːðə(r)/",
			options: ["echtgenoot", "grootvader / opa", "grootmoeder / oma", "ouder"],
		},
		{
			id: "enL1-23",
			type: "vocab",
			prompt: "oma",
			answer: "grandma",
			direction: "nl->en",
			hint: "n /ˈɡrænmɑː/",
		},
		{
			id: "enL1-24",
			type: "vocab",
			prompt: "grandmother",
			answer: "grootmoeder / oma",
			alternatives: ["grootmoeder", "oma"],
			direction: "en->nl",
			hint: "n /ˈɡrænmʌðə(r)/",
			options: ["papa", "nicht (het kind van je broer of zus)", "oom", "grootmoeder / oma"],
		},
		{
			id: "enL1-25",
			type: "vocab",
			prompt: "grootouder",
			answer: "grandparent",
			direction: "nl->en",
			hint: "n /ˈɡrænpeərənt/",
		},
		{
			id: "enL1-26",
			type: "vocab",
			prompt: "grandson",
			answer: "kleinzoon",
			direction: "en->nl",
			hint: "n /ˈɡrænsʌn/",
			options: ["kleinkinderen", "papa", "kleinzoon", "moeder"],
		},
		{
			id: "enL1-27",
			type: "vocab",
			prompt: "hardwerkend",
			answer: "hard-working",
			direction: "nl->en",
			hint: "adj /ˌhɑːd ˈwɜːkɪŋ/",
		},
		{
			id: "enL1-28",
			type: "vocab",
			prompt: "honest",
			answer: "eerlijk",
			direction: "en->nl",
			hint: "adj /ˈɒnɪst/",
			options: ["enthousiast, dol (als in: dol op iets zijn)", "recht", "eerlijk", "trots"],
		},
		{
			id: "enL1-29",
			type: "vocab",
			prompt: "echtgenoot",
			answer: "husband",
			direction: "nl->en",
			hint: "n /ˈhʌzbənd/",
		},
		{
			id: "enL1-30",
			type: "vocab",
			prompt: "interested",
			answer: "geïnteresseerd",
			direction: "en->nl",
			hint: "adj /ˈɪntrəstɪd/",
			options: ["verstandig", "trots", "geïnteresseerd", "blauw"],
		},
		{
			id: "enL1-31",
			type: "vocab",
			prompt: "enthousiast, dol (als in: dol op iets zijn)",
			answer: "keen",
			direction: "nl->en",
			hint: "adj /kiːn/",
		},
		{
			id: "enL1-32",
			type: "vocab",
			prompt: "load (the dishwasher)",
			answer: "(de vaatwasser) inruimen",
			direction: "en->nl",
			hint: "v /ləʊd/",
			options: ["(de tafel) dekken", "(eten) koken", "boodschappen doen", "(de vaatwasser) inruimen"],
		},
		{
			id: "enL1-33",
			type: "vocab",
			prompt: "lang",
			answer: "long",
			direction: "nl->en",
			hint: "adj /lɒŋ/",
		},
		{
			id: "enL1-34",
			type: "vocab",
			prompt: "mother",
			answer: "moeder",
			direction: "en->nl",
			hint: "n /ˈmʌðə(r)/",
			options: ["moeder", "nicht (het kind van je broer of zus)", "oom", "grootouder"],
		},
		{
			id: "enL1-35",
			type: "vocab",
			prompt: "snor",
			answer: "moustache",
			direction: "nl->en",
			hint: "n /məˈstɑːʃ/",
		},
		{
			id: "enL1-36",
			type: "vocab",
			prompt: "mum",
			answer: "mama",
			direction: "en->nl",
			hint: "n /mʌm/",
			options: ["mama", "neef / nicht (het kind van je oom en tante)", "papa", "echtgenoot"],
		},
		{
			id: "enL1-37",
			type: "vocab",
			prompt: "neef (het kind van je broer of zus)",
			answer: "nephew",
			direction: "nl->en",
			hint: "n /ˈnefjuː/",
		},
		{
			id: "enL1-38",
			type: "vocab",
			prompt: "niece",
			answer: "nicht (het kind van je broer of zus)",
			alternatives: ["nicht"],
			direction: "en->nl",
			hint: "n /niːs/",
			options: ["broer", "tante", "nicht (het kind van je broer of zus)", "neef / nicht (het kind van je oom en tante)"],
		},
		{
			id: "enL1-39",
			type: "vocab",
			prompt: "ouder",
			answer: "parent",
			direction: "nl->en",
			hint: "n /ˈpeərənt/",
		},
		{
			id: "enL1-40",
			type: "vocab",
			prompt: "patient",
			answer: "patiënt",
			direction: "en->nl",
			hint: "n /ˈpeɪʃnt/",
			options: ["patiënt", "bril", "opa", "snor"],
		},
		{
			id: "enL1-41",
			type: "vocab",
			prompt: "beleefd",
			answer: "polite",
			direction: "nl->en",
			hint: "adj /pəˈlaɪt/",
		},
		{
			id: "enL1-42",
			type: "vocab",
			prompt: "proud",
			answer: "trots",
			direction: "en->nl",
			hint: "adj /praʊd/",
			options: ["geïnteresseerd", "verstandig", "bezorgd", "trots"],
		},
		{
			id: "enL1-43",
			type: "vocab",
			prompt: "verstandig",
			answer: "sensible",
			direction: "nl->en",
			hint: "adj /ˈsensəbl/",
		},
		{
			id: "enL1-44",
			type: "vocab",
			prompt: "set (the table)",
			answer: "(de tafel) dekken",
			direction: "en->nl",
			hint: "v /set/",
			options: ["strijken", "(het huis) schoonmaken", "(de vaatwasser) inruimen", "(de tafel) dekken"],
		},
		{
			id: "enL1-45",
			type: "vocab",
			prompt: "kort",
			answer: "short",
			direction: "nl->en",
			hint: "adj /ʃɔːt/",
		},
		{
			id: "enL1-46",
			type: "vocab",
			prompt: "sister",
			answer: "zus",
			direction: "en->nl",
			hint: "n /ˈsɪstə(r)/",
			options: ["grootvader / opa", "vrouw, echtgenote", "echtgenoot", "zus"],
		},
		{
			id: "enL1-47",
			type: "vocab",
			prompt: "zoon",
			answer: "son",
			direction: "nl->en",
			hint: "n /sʌn/",
		},
		{
			id: "enL1-48",
			type: "vocab",
			prompt: "straight",
			answer: "recht",
			direction: "en->nl",
			hint: "adj /streɪt/",
			options: ["eerlijk", "boos", "recht", "hardwerkend"],
		},
		{
			id: "enL1-49",
			type: "vocab",
			prompt: "(mijn slaapkamer) opruimen",
			answer: "tidy (my bedroom)",
			alternatives: ["tidy"],
			direction: "nl->en",
			hint: "v /ˈtaɪdi/",
		},
		{
			id: "enL1-50",
			type: "vocab",
			prompt: "uncle",
			answer: "oom",
			direction: "en->nl",
			hint: "n /ˈʌŋkl/",
			options: ["kleindochter", "oom", "tante", "oma"],
		},
		{
			id: "enL1-51",
			type: "vocab",
			prompt: "afwassen",
			answer: "wash (the dishes)",
			alternatives: ["wash"],
			direction: "nl->en",
			hint: "v /wɒʃ/",
		},
		{
			id: "enL1-52",
			type: "vocab",
			prompt: "wavy",
			answer: "golvend",
			direction: "en->nl",
			hint: "adj /ˈweɪvi/",
			options: ["recht", "golvend", "trots", "verstandig"],
		},
		{
			id: "enL1-53",
			type: "vocab",
			prompt: "vrouw, echtgenote",
			answer: "wife",
			direction: "nl->en",
			hint: "n /waɪf/",
		},
		{
			id: "enL1-54",
			type: "vocab",
			prompt: "worried",
			answer: "bezorgd",
			direction: "en->nl",
			hint: "adj /ˈwɜːrid/",
			options: ["trots", "verstandig", "blauw", "bezorgd"],
		},
	],
} as const;

export const chapter: Chapter = chapterSchema.parse(rawChapter);